# Effort Metrics

## Measure the metrics

In [1]:
# mono_repository_path = f"./data/repositories"
# monomorph_results = {
#     ("microrefact", "7ep-demo", "manual"): {
#         "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/7ep-demo/refacteval-quantitative/Ayyoub_results/refactored/7ep-demo",
#         "repo_path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/7ep-demo/refacteval-quantitative",
#         "microservices": ["0", "1", "2", "3"],
#         "start_commits": {
#             "0": "04991d69b854f420044b0122c52dac1dabfa0465",
#             "1": "1883b42555f5b394f83531f8ffd7c1572c97a51e",
#             "2": "396f6504612859bd34348a8ed2c45bd04cf304cc",
#             "3": "fcbd3dc7ed422eb4677a7dfd74201a3898b88c57"
#         },
#         "end_commits": {
#             "0": "b5681758172d4f9d8720a49b9e6a0ac488eec605",
#             "1": "04991d69b854f420044b0122c52dac1dabfa0465",
#             "2": "fcbd3dc7ed422eb4677a7dfd74201a3898b88c57",
#             "3": "1883b42555f5b394f83531f8ffd7c1572c97a51e"
#         }
#     },
#     ("microrefact", "jpetstore-6", "manual"): {
#         "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/jpetstore-6/refacteval-quantitative/Ayyoub_results/refactored/jpetstore-6",
#         "repo_path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/jpetstore-6/refacteval-quantitative",
#         "microservices": ["0", "1", "2"],
#         "start_commits": {
#             "0": "PLACEHOLDER",
#             "1": "PLACEHOLDER",
#             "2": "PLACEHOLDER",
#         },
#         "end_commits": {
#             "0": "PLACEHOLDER",
#             "1": "PLACEHOLDER",
#             "2": "PLACEHOLDER",
#         }
#     },
#     ("microrefact", "spring-petclinic", "manual"): {
#         "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/spring-petclinic/refacteval-quantitative/spring-petclinic",
#         "repo_path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/spring-petclinic/refacteval-quantitative",
#         "microservices": ["0", "1", "2"],
#         "start_commits": {
#             "0": "PLACEHOLDER",
#             "1": "PLACEHOLDER",
#             "2": "PLACEHOLDER",
#         },
#         "end_commits": {
#             "0": "PLACEHOLDER",
#             "1": "PLACEHOLDER",
#             "2": "PLACEHOLDER",
#         }
#     },
# }

In [21]:
mono_repository_path = f"./data/repositories"
monomorph_results = {
    ("microrefact", "7ep-demo", "manual"): {
        "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/7ep-demo/refacteval-quantitative/Ayyoub_results/refactored/7ep-demo",
        "repo_path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/7ep-demo/refacteval-quantitative",
        "microservices": ["0", "1", "2", "3"],
        "start_commits": {
            "0": "396f6504612859bd34348a8ed2c45bd04cf304cc",
            "1": "396f6504612859bd34348a8ed2c45bd04cf304cc",
            "2": "396f6504612859bd34348a8ed2c45bd04cf304cc",
            "3": "396f6504612859bd34348a8ed2c45bd04cf304cc"
        },
        "end_commits": {
            "0": "b5681758172d4f9d8720a49b9e6a0ac488eec605",
            "1": "b5681758172d4f9d8720a49b9e6a0ac488eec605",
            "2": "b5681758172d4f9d8720a49b9e6a0ac488eec605",
            "3": "b5681758172d4f9d8720a49b9e6a0ac488eec605"
        }
    },
    ("microrefact", "jpetstore-6", "manual"): {
        "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/jpetstore-6/refacteval-quantitative/Ayyoub_results/refactored/jpetstore-6",
        "repo_path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/jpetstore-6/refacteval-quantitative",
        "microservices": ["0", "1", "2"],
        "start_commits": {
            "0": "77507a149b6cd96d2d45742d182187d6216851a0",
            "1": "77507a149b6cd96d2d45742d182187d6216851a0",
            "2": "77507a149b6cd96d2d45742d182187d6216851a0",
        },
        "end_commits": {
            "0": "6bd2761b1833c03ec47e9c32b30cf63ea6cfb4c2",
            "1": "6bd2761b1833c03ec47e9c32b30cf63ea6cfb4c2",
            "2": "6bd2761b1833c03ec47e9c32b30cf63ea6cfb4c2",
        }
    },
    ("microrefact", "spring-petclinic", "manual"): {
        "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/spring-petclinic/refacteval-quantitative/spring-petclinic",
        "repo_path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/spring-petclinic/refacteval-quantitative",
        "microservices": ["0", "1", "2"],
        "start_commits": {
            "0": "25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2",
            "1": "25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2",
            "2": "25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2",
        },
        "end_commits": {
            "0": "1ea2660eefa7f1bea8cb4875f483d81faaf1eaa6",
            "1": "1ea2660eefa7f1bea8cb4875f483d81faaf1eaa6",
            "2": "1ea2660eefa7f1bea8cb4875f483d81faaf1eaa6",
        },
        "excluded_commits": {
            "1": [
                "ae27879e9ce38efddbd820f0802d9f6a0c036e0c",  # added missing test class
            ],
        }
    },
    ("microrefact", "spring-petclinic", "excluding_bloated_commits"): {
        "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/spring-petclinic/refacteval-quantitative/spring-petclinic",
        "repo_path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_quantitative_eval/spring-petclinic/refacteval-quantitative",
        "microservices": ["0", "1", "2"],
        "start_commits": {
            "0": "25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2",
            "1": "25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2",
            "2": "25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2",
        },
        "end_commits": {
            "0": "1ea2660eefa7f1bea8cb4875f483d81faaf1eaa6",
            "1": "1ea2660eefa7f1bea8cb4875f483d81faaf1eaa6",
            "2": "1ea2660eefa7f1bea8cb4875f483d81faaf1eaa6",
        },
        "excluded_commits": {
            "0": [
                "9c6e5141fb02ba703a14a5762c92d3dd0585055e", # spring-javaformat changes
                "3ae43f808a44111269aaf43936db41e18d1a2b2a" # checkstyle changes
            ],
            "1": [
                "ae27879e9ce38efddbd820f0802d9f6a0c036e0c",  # added missing test class
                "cb52314aaa38dc4c0e7dedc7f77ece6b645a37a0", # spring-javaformat changes
                "00678797a48d252afff76872f494a8d9a53eeabf" # checkstyle changes
            ],
            "2": [
                "0bd6361541d179dc9a80e9cfc05a24eb8bfa6876", # spring-javaformat changes
                "40272c43ee19f412b04b416603597c4d62c48bd8" # checkstyle changes
            ],
        }
    },
}

In [24]:
import os

from refacteval.versioning.commits import RepositoryAnalyzer

all_results = monomorph_results.copy()

for benchmark, app, run_name in monomorph_results:
    print(f"Benchmark: {benchmark}, App: {app}, Run Name: {run_name}")
    results_path = monomorph_results[(benchmark, app, run_name)]["path"]
    microservices = monomorph_results[(benchmark, app, run_name)]["microservices"]
    mono_path = os.path.abspath(f"{mono_repository_path}/qualitative_eval/{app}")
    all_results[(benchmark, app, run_name)]["monolith_path"] = mono_path
    all_results[(benchmark, app, run_name)]["results"] = dict()
    for ms in microservices:
        print(f"  Microservice: {ms}")
        ms_path = f"{results_path}/{ms}"
        # ms_path = results_path
        repository_path = monomorph_results[(benchmark, app, run_name)].get("repo_path", ms_path)
        start_commit = monomorph_results[(benchmark, app, run_name)].get("start_commits", {}).get(ms, None)
        end_commit = monomorph_results[(benchmark, app, run_name)].get("end_commits", {}).get(ms, 'HEAD')
        excluded_commits = monomorph_results[(benchmark, app, run_name)].get("excluded_commits", {}).get(ms, None)
        analyzer = RepositoryAnalyzer(repository_path, ms_path)
        metrics = analyzer.get_comprehensive_refactoring_metrics_with_monolith(
            monolith_repo_path=mono_path,
            start_commit=start_commit,
            end_commit=end_commit,
            exclude_commits=excluded_commits
        )
        all_results[(benchmark, app, run_name)]["results"][ms] = {
            "path": ms_path,
            "repo_path": repository_path,
            "metrics": metrics,
            "start_commit": start_commit
        }
        # print(f"    Metrics: {metrics}")
        print("    " + "-"*50)
    print("" + "="*100)

Benchmark: microrefact, App: 7ep-demo, Run Name: manual
  Microservice: 0
    --------------------------------------------------
  Microservice: 1
    --------------------------------------------------
  Microservice: 2
    --------------------------------------------------
  Microservice: 3
    --------------------------------------------------
====================================================================================================
Benchmark: microrefact, App: jpetstore-6, Run Name: manual
  Microservice: 0
    --------------------------------------------------
  Microservice: 1
    --------------------------------------------------
  Microservice: 2
    --------------------------------------------------
====================================================================================================
Benchmark: microrefact, App: spring-petclinic, Run Name: manual
  Microservice: 0
    --------------------------------------------------
  Microservice: 1
    --------------------------------------------------
  Microservice: 2
    --------------------------------------------------
====================================================================================================
Benchmark: microrefact, App: spring-petclinic, Run Name: excluding_bloated_commits
  Microservice: 0
    --------------------------------------------------
  Microservice: 1
    --------------------------------------------------
  Microservice: 2
    --------------------------------------------------
====================================================================================================

In [25]:
# save_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/refact-effort/microrefact_metrics_7epdemo-4.json"
save_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/refact-effort/microrefact_metrics.json"
import json, os



results_to_serialize = {
    f"{benchmark}/{app}/{run_name}": {
        "benchmark": benchmark,
        "app": app,
        "run_name": run_name
    } | data for (benchmark, app, run_name), data in all_results.items()
}

with open(save_path, "w") as f:
    json.dump(results_to_serialize, f, indent=4)

## Analyze the metrics

In [6]:
import json, os

save_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/refact-effort/microrefact_metrics.json"

with open(save_path, "r") as f:
    results_to_serialize = json.load(f)

In [2]:
import pandas as pd

columns = [
    "benchmark", "app", "run_name", "microservice",
    "start_commit", "end_commit", "excluded_commits",
    "global_line_changes", "global_hunk_changes", "global_file_changes", "commit_count",
    "total_line_changes", "total_hunk_changes", "total_file_changes",
    "per_commit_line_changes", "per_commit_hunk_changes", "per_commit_file_changes",
    "global_new_artifacts_updated", "global_old_artifacts_updated", "global_new_artifacts_created",
    "total_new_artifacts_updated", "total_old_artifacts_updated", "total_new_artifacts_created",
    "per_commit_new_artifacts_updated", "per_commit_old_artifacts_updated", "per_commit_new_artifacts_created",
    "new_relevant_artifacts_updated", "old_relevant_artifacts_updated", "new_relevant_artifacts_created",
    "all_new_relevant_artifacts", "all_old_relevant_artifacts", "total_relevant_artifacts",
    "new_relevant_artifact_update_ratio", "old_relevant_artifact_update_ratio", "all_relevant_artifact_update_ratio",]

In [3]:
important_metrics = [
    "global_line_changes", "commit_count", "new_relevant_artifact_update_ratio", "new_relevant_artifacts_updated", "all_new_relevant_artifacts", "old_relevant_artifact_update_ratio", "old_relevant_artifacts_updated", "all_old_relevant_artifacts", "global_hunk_changes"
]
maybe_metrics = [
    "total_line_changes", "global_file_changes", "all_relevant_artifact_update_ratio",
]

In [4]:
df = pd.DataFrame(columns=columns)

In [8]:
rows = []
for run_key, data in results_to_serialize.items():
    benchmark = data["benchmark"]
    app = data["app"]
    run_name = data["run_name"]
    for ms, results in data["results"].items():
        row = {
            "benchmark": benchmark,
            "app": app,
            "run_name": run_name,
            "microservice": ms,
            "start_commit": results["start_commit"],
            "end_commit": "HEAD",
        }
        metrics = results["metrics"]
        row["excluded_commits"] = "///".join(metrics["configuration"]["excluded_commits"])
        cd_metrics = metrics["code_change_metrics"]
        row["global_line_changes"] = cd_metrics["global_metrics"]["gnlc"]
        row["global_hunk_changes"] = cd_metrics["global_metrics"]["gnh"]
        row["global_file_changes"] = cd_metrics["global_metrics"]["gnf"]
        row["commit_count"] = cd_metrics["global_metrics"]["commit_count"]
        row["total_line_changes"] = cd_metrics["total_metrics"]["total_nlc"]
        row["total_hunk_changes"] = cd_metrics["total_metrics"]["total_nh"]
        row["total_file_changes"] = cd_metrics["total_metrics"]["total_nf"]
        row["per_commit_line_changes"] = cd_metrics["per_commit_averages"]["nlc_per_commit"]
        row["per_commit_hunk_changes"] = cd_metrics["per_commit_averages"]["hunks_per_commit"]
        row["per_commit_file_changes"] = cd_metrics["per_commit_averages"]["files_per_commit"]
        re_metrics = metrics["refactoring_effort_metrics"]
        row["global_new_artifacts_updated"] = re_metrics["global_metrics"]["new_artifacts_updated"]
        row["global_old_artifacts_updated"] = re_metrics["global_metrics"]["old_artifacts_updated"]
        row["global_new_artifacts_created"] = re_metrics["global_metrics"]["new_artifacts_created"]
        row["new_relevant_artifacts_updated"] = re_metrics["global_metrics"]["new_relevant_artifacts_updated"]
        row["old_relevant_artifacts_updated"] = re_metrics["global_metrics"]["old_relevant_artifacts_updated"]
        row["new_relevant_artifacts_created"] = re_metrics["global_metrics"]["new_relevant_artifacts_created"]
        row["all_new_relevant_artifacts"] = re_metrics["global_metrics"]["all_new_relevant_artifacts_in_repo"]
        row["all_old_relevant_artifacts"] = re_metrics["global_metrics"]["all_old_relevant_artifacts_in_repo"]
        row["total_relevant_artifacts"] = re_metrics["global_metrics"]["total_relevant_artifacts_in_repo"]
        row["total_new_artifacts_updated"] = re_metrics["total_metrics"]["total_new_artifacts_updated"]
        row["total_old_artifacts_updated"] = re_metrics["total_metrics"]["total_old_artifacts_updated"]
        row["total_new_artifacts_created"] = re_metrics["total_metrics"]["total_new_artifacts_created"]
        row["per_commit_new_artifacts_updated"] = re_metrics["per_commit_averages"]["new_artifacts_updated_per_commit"]
        row["per_commit_old_artifacts_updated"] = re_metrics["per_commit_averages"]["old_artifacts_updated_per_commit"]
        row["per_commit_new_artifacts_created"] = re_metrics["per_commit_averages"]["new_artifacts_created_per_commit"]
        row["new_relevant_artifact_update_ratio"] = (row["new_relevant_artifacts_updated"] + row["new_relevant_artifacts_created"]) / row["all_new_relevant_artifacts"] if row["all_new_relevant_artifacts"] > 0 else 0
        row["old_relevant_artifact_update_ratio"] = row["old_relevant_artifacts_updated"] / row["all_old_relevant_artifacts"] if row["all_old_relevant_artifacts"] > 0 else 0
        row["all_relevant_artifact_update_ratio"] = (
            row["new_relevant_artifacts_updated"] + row["old_relevant_artifacts_updated"] + row["new_relevant_artifacts_created"]
        ) / row["total_relevant_artifacts"] if row["total_relevant_artifacts"] > 0 else 0
        # df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
        rows.append(row)
df = pd.DataFrame(rows, columns=columns)

In [9]:
df.shape

(13, 35)

In [10]:
df

,benchmark,app,run_name,microservice,start_commit,end_commit,excluded_commits,global_line_changes,global_hunk_changes,global_file_changes,...,per_commit_new_artifacts_created,new_relevant_artifacts_updated,old_relevant_artifacts_updated,new_relevant_artifacts_created,all_new_relevant_artifacts,all_old_relevant_artifacts,total_relevant_artifacts,new_relevant_artifact_update_ratio,old_relevant_artifact_update_ratio,all_relevant_artifact_update_ratio
0,microrefact,7ep-demo,manual,0,396f6504612859bd34348a8ed2c45bd04cf304cc,HEAD,,1942,3,17,...,0.00,1,16,0,3,36,39,0.333333,0.444444,0.435897
1,microrefact,7ep-demo,manual,1,396f6504612859bd34348a8ed2c45bd04cf304cc,HEAD,,3348,8,24,...,0.50,1,19,4,7,40,47,0.714286,0.475000,0.510638
2,microrefact,7ep-demo,manual,2,396f6504612859bd34348a8ed2c45bd04cf304cc,HEAD,,760,3,15,...,0.00,0,12,0,6,24,30,0.000000,0.500000,0.400000
3,microrefact,7ep-demo,manual,3,396f6504612859bd34348a8ed2c45bd04cf304cc,HEAD,,1358,2,11,...,0.25,0,10,1,2,21,23,0.500000,0.476190,0.478261
4,microrefact,jpetstore-6,manual,0,77507a149b6cd96d2d45742d182187d6216851a0,HEAD,,58,1,6,...,0.00,3,3,0,5,10,15,0.600000,0.300000,0.400000
5,microrefact,jpetstore-6,manual,1,77507a149b6cd96d2d45742d182187d6216851a0,HEAD,,69,1,9,...,0.00,7,2,0,8,17,25,0.875000,0.117647,0.360000
6,microrefact,jpetstore-6,manual,2,77507a149b6cd96d2d45742d182187d6216851a0,HEAD,,155,1,17,...,0.00,9,8,0,11,20,31,0.818182,0.400000,0.548387
7,microrefact,spring-petclinic,manual,0,25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2,HEAD,,1858,22,32,...,1.83,2,17,6,8,24,32,1.000000,0.708333,0.781250
8,microrefact,spring-petclinic,manual,1,25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2,HEAD,ae27879e9ce38efddbd820f0802d9f6a0c036e0c,1312,20,32,...,1.50,4,16,4,8,23,31,1.000000,0.695652,0.774194
9,microrefact,spring-petclinic,manual,2,25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2,HEAD,,903,14,24,...,1.40,4,11,2,6,14,20,1.000000,0.785714,0.850000
10,microrefact,spring-petclinic,excluding_bloated_commits,0,25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2,HEAD,9c6e5141fb02ba703a14a5762c92d3dd0585055e///3ae...,1858,22,32,...,2.25,1,3,6,8,24,32,0.875000,0.125000,0.312500
11,microrefact,spring-petclinic,excluding_bloated_commits,1,25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2,HEAD,ae27879e9ce38efddbd820f0802d9f6a0c036e0c///cb5...,1312,20,32,...,1.75,2,3,4,8,23,31,0.750000,0.130435,0.290323
12,microrefact,spring-petclinic,excluding_bloated_commits,2,25fd4d40e6b2321fe1b45ac4f9ad39880d0fe8d2,HEAD,0bd6361541d179dc9a80e9cfc05a24eb8bfa6876///402...,903,14,24,...,1.67,2,3,2,6,14,20,0.666667,0.214286,0.350000

In [11]:
save_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/refact-effort/microrefact_metrics.csv"
df.to_csv(save_path, index=False)

## Parse the metrics

In [1]:
import pandas as pd

save_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/refact-effort/microrefact_metrics.csv"
df = pd.read_csv(save_path)

In [7]:
import pandas as pd
import numpy as np

def format_rate_col(row, generated=True):
    if generated:
        updated_col = 'new_relevant_artifacts_updated'
        all_col = 'all_new_relevant_artifacts'
        rate_col = 'GAR-R'
    else:
        updated_col = 'old_relevant_artifacts_updated'
        all_col = 'all_old_relevant_artifacts'
        rate_col = 'MAR-R'
    return f"{int(row[updated_col])} of {int(row[all_col])} ({row[rate_col]*100:.1f}%)" if row[all_col] > 0 else "0 of 0 (0.0%)"

def extract_metrics(df):
    """
    Extract metrics from the dataframe containing correction agent data.

    Parameters:
    df (pd.DataFrame): Input dataframe with correction agent results

    Returns:
    pd.DataFrame: DataFrame with extracted metrics
    """

    # Create a copy of the dataframe to avoid modifying the original
    metrics_df = df.copy()

    metrics_df['success_rate'] = True
    metrics_df['commit_count'] = metrics_df['commit_count']
    metrics_df['GLOC'] = metrics_df['global_line_changes']
    metrics_df['TLOC'] = metrics_df['total_line_changes']
    metrics_df['GHC'] = metrics_df['global_hunk_changes']
    metrics_df['GFC'] = metrics_df['global_file_changes']
    metrics_df['GAR-R'] = np.where(
        metrics_df['all_new_relevant_artifacts'] > 0,
        metrics_df['new_relevant_artifacts_updated'] / metrics_df['all_new_relevant_artifacts'],
        0
    )
    metrics_df['MAR-R'] = np.where(
        metrics_df['all_old_relevant_artifacts'] > 0,
        metrics_df['old_relevant_artifacts_updated'] / metrics_df['all_old_relevant_artifacts'],
        0
    )

    # Create formatted ratio columns
    # Generated Artifacts Ratio formatted as "x of y (z%)"
    metrics_df['GAR'] = metrics_df.apply(
        lambda row: format_rate_col(row, generated=True),
        axis=1
    )

    # Migrated Artifacts Ratio formatted as "x of y (z%)"
    metrics_df['MAR'] = metrics_df.apply(
        lambda row: format_rate_col(row, generated=False),
        axis=1
    )

    # Select the key metrics columns for the final result
    metrics_columns = [
        # Identifier columns
        'benchmark', 'app', 'run_name', 'microservice',

        # Core metrics
        'success_rate',
        'commit_count',
        'GLOC',
        'TLOC',
        'GHC',
        'GFC',
        'GAR',
        'MAR',

        # Formatted ratio columns
        # 'Generated_Artifacts_Ratio_Formatted',
        # 'Migrated_Artifacts_Ratio_Formatted',
        'new_relevant_artifacts_updated',
        'all_new_relevant_artifacts',
        'GAR-R',
        'old_relevant_artifacts_updated',
        'all_old_relevant_artifacts',
        'MAR-R',
    ]

    return metrics_df[metrics_columns]

In [14]:
metrics_df = extract_metrics(df)

In [7]:
metrics_df["key"] = metrics_df.apply(lambda row: f"{row['benchmark']}/{row['app']}/{row['run_name']}/{row['microservice']}", axis=1)
metrics_df = metrics_df.set_index("key")
metrics_df

,benchmark,app,run_name,microservice,success_rate,commit_count,GLOC,TLOC,GHC,GFC,GAR,MAR,new_relevant_artifacts_updated,all_new_relevant_artifacts,GAR-R,old_relevant_artifacts_updated,all_old_relevant_artifacts,MAR-R
key,,,,,,,,,,,,,,,,,,
microrefact/7ep-demo/manual/0,microrefact,7ep-demo,manual,0,True,7,1942,1944,3,17,1 of 3 (33.3%),16 of 36 (44.4%),1,3,0.333333,16,36,0.444444
microrefact/7ep-demo/manual/1,microrefact,7ep-demo,manual,1,True,8,3348,3348,8,24,1 of 7 (14.3%),19 of 40 (47.5%),1,7,0.142857,19,40,0.475000
microrefact/7ep-demo/manual/2,microrefact,7ep-demo,manual,2,True,6,760,760,3,15,0 of 6 (0.0%),12 of 24 (50.0%),0,6,0.000000,12,24,0.500000
microrefact/7ep-demo/manual/3,microrefact,7ep-demo,manual,3,True,4,1358,1358,2,11,0 of 2 (0.0%),10 of 21 (47.6%),0,2,0.000000,10,21,0.476190
microrefact/jpetstore-6/manual/0,microrefact,jpetstore-6,manual,0,True,6,58,62,1,6,3 of 5 (60.0%),3 of 10 (30.0%),3,5,0.600000,3,10,0.300000
microrefact/jpetstore-6/manual/1,microrefact,jpetstore-6,manual,1,True,6,69,69,1,9,7 of 8 (87.5%),2 of 17 (11.8%),7,8,0.875000,2,17,0.117647
microrefact/jpetstore-6/manual/2,microrefact,jpetstore-6,manual,2,True,14,155,159,1,17,9 of 11 (81.8%),8 of 20 (40.0%),9,11,0.818182,8,20,0.400000
microrefact/spring-petclinic/manual/0,microrefact,spring-petclinic,manual,0,True,6,1858,1870,22,32,2 of 8 (25.0%),17 of 24 (70.8%),2,8,0.250000,17,24,0.708333
microrefact/spring-petclinic/manual/1,microrefact,spring-petclinic,manual,1,True,6,1312,1262,20,32,4 of 8 (50.0%),16 of 23 (69.6%),4,8,0.500000,16,23,0.695652
microrefact/spring-petclinic/manual/2,microrefact,spring-petclinic,manual,2,True,5,903,911,14,24,4 of 6 (66.7%),11 of 14 (78.6%),4,6,0.666667,11,14,0.785714
microrefact/spring-petclinic/excluding_bloated_commits/0,microrefact,spring-petclinic,excluding_bloated_commits,0,True,4,1858,230,22,32,1 of 8 (12.5%),3 of 24 (12.5%),1,8,0.125000,3,24,0.125000
microrefact/spring-petclinic/excluding_bloated_commits/1,microrefact,spring-petclinic,excluding_bloated_commits,1,True,4,1312,310,20,32,2 of 8 (25.0%),3 of 23 (13.0%),2,8,0.250000,3,23,0.130435
microrefact/spring-petclinic/excluding_bloated_commits/2,microrefact,spring-petclinic,excluding_bloated_commits,2,True,3,903,333,14,24,2 of 6 (33.3%),3 of 14 (21.4%),2,6,0.333333,3,14,0.214286

In [8]:
save_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/refact-effort/microrefact_filtered_metrics.csv"
metrics_df.to_csv(save_path)

## Create table

In [1]:
import pandas as pd

save_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/refact-effort/microrefact_filtered_metrics.csv"
metrics_df = pd.read_csv(save_path, index_col="key")

In [13]:
# manual run metrics
single_run_metrics = metrics_df[metrics_df.run_name=="manual"].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
num_cols = ['success_rate',
       'commit_count', 'GLOC', 'TLOC', 'GFC',
       'new_relevant_artifacts_updated', 'all_new_relevant_artifacts', 'GAR-R',
       'old_relevant_artifacts_updated', 'all_old_relevant_artifacts',
       'MAR-R']
single_run_metrics[num_cols]
mean_overall_line = single_run_metrics[num_cols].mean()
mean_overall_line

success_rate                         1.000000
commit_count                         6.800000
GLOC                              1176.300000
TLOC                              1174.300000
GFC                                 18.700000
new_relevant_artifacts_updated       3.100000
all_new_relevant_artifacts           6.400000
GAR-R                                0.418604
old_relevant_artifacts_updated      11.400000
all_old_relevant_artifacts          22.900000
MAR-R                                0.490298
dtype: float64

In [4]:
def get_overall_row(dfm):
    sum_cols = ['new_relevant_artifacts_updated', 'all_new_relevant_artifacts', 'old_relevant_artifacts_updated', 'all_old_relevant_artifacts']
    mean_cols = [
        'success_rate',  'GAR-R',  'MAR-R',
    ]
    median_cols = ['commit_count', 'GLOC', 'TLOC', 'GFC']
    overall_row = pd.Series(['Overall', "Overall"] + [None]*(len(dfm.columns)-2), index=dfm.columns)
    overall_row[sum_cols] = dfm[sum_cols].sum()
    overall_row[mean_cols] = dfm[mean_cols].mean()
    overall_row[median_cols] = dfm[median_cols].median()
    overall_row['GAR'] = format_rate_col(overall_row, generated=True)
    overall_row['MAR'] = format_rate_col(overall_row, generated=False)
    return overall_row

In [15]:
single_run_metrics = metrics_df[metrics_df.run_name=="manual"].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
overall_row = get_overall_row(single_run_metrics)
single_run_metrics = pd.concat([single_run_metrics, overall_row.to_frame().T], axis=0)
single_run_metrics

,app,microservice,success_rate,commit_count,GLOC,TLOC,GFC,GAR,MAR,new_relevant_artifacts_updated,all_new_relevant_artifacts,GAR-R,old_relevant_artifacts_updated,all_old_relevant_artifacts,MAR-R
0,7ep-demo,0,True,7,1942,1944,17,1 of 3 (33.3%),16 of 36 (44.4%),1,3,0.333333,16,36,0.444444
1,7ep-demo,1,True,8,3348,3348,24,1 of 7 (14.3%),19 of 40 (47.5%),1,7,0.142857,19,40,0.475
2,7ep-demo,2,True,6,760,760,15,0 of 6 (0.0%),12 of 24 (50.0%),0,6,0.0,12,24,0.5
3,7ep-demo,3,True,4,1358,1358,11,0 of 2 (0.0%),10 of 21 (47.6%),0,2,0.0,10,21,0.47619
4,jpetstore-6,0,True,6,58,62,6,3 of 5 (60.0%),3 of 10 (30.0%),3,5,0.6,3,10,0.3
5,jpetstore-6,1,True,6,69,69,9,7 of 8 (87.5%),2 of 17 (11.8%),7,8,0.875,2,17,0.117647
6,jpetstore-6,2,True,14,155,159,17,9 of 11 (81.8%),8 of 20 (40.0%),9,11,0.818182,8,20,0.4
7,spring-petclinic,0,True,6,1858,1870,32,2 of 8 (25.0%),17 of 24 (70.8%),2,8,0.25,17,24,0.708333
8,spring-petclinic,1,True,6,1312,1262,32,4 of 8 (50.0%),16 of 23 (69.6%),4,8,0.5,16,23,0.695652
9,spring-petclinic,2,True,5,903,911,24,4 of 6 (66.7%),11 of 14 (78.6%),4,6,0.666667,11,14,0.785714
0,Overall,Overall,1.0,6.0,1107.5,1086.5,17.0,31 of 64 (41.9%),114 of 229 (49.0%),31,64,0.418604,114,229,0.490298

In [2]:
metrics_df["microservice"] = metrics_df["microservice"].astype(str)

In [18]:
metrics_df

,benchmark,app,run_name,microservice,success_rate,commit_count,GLOC,TLOC,GHC,GFC,GAR,MAR,new_relevant_artifacts_updated,all_new_relevant_artifacts,GAR-R,old_relevant_artifacts_updated,all_old_relevant_artifacts,MAR-R
key,,,,,,,,,,,,,,,,,,
microrefact/7ep-demo/manual/0,microrefact,7ep-demo,manual,0,True,7,1942,1944,3,17,1 of 3 (33.3%),16 of 36 (44.4%),1,3,0.333333,16,36,0.444444
microrefact/7ep-demo/manual/1,microrefact,7ep-demo,manual,1,True,8,3348,3348,8,24,1 of 7 (14.3%),19 of 40 (47.5%),1,7,0.142857,19,40,0.475000
microrefact/7ep-demo/manual/2,microrefact,7ep-demo,manual,2,True,6,760,760,3,15,0 of 6 (0.0%),12 of 24 (50.0%),0,6,0.000000,12,24,0.500000
microrefact/7ep-demo/manual/3,microrefact,7ep-demo,manual,3,True,4,1358,1358,2,11,0 of 2 (0.0%),10 of 21 (47.6%),0,2,0.000000,10,21,0.476190
microrefact/jpetstore-6/manual/0,microrefact,jpetstore-6,manual,0,True,6,58,62,1,6,3 of 5 (60.0%),3 of 10 (30.0%),3,5,0.600000,3,10,0.300000
microrefact/jpetstore-6/manual/1,microrefact,jpetstore-6,manual,1,True,6,69,69,1,9,7 of 8 (87.5%),2 of 17 (11.8%),7,8,0.875000,2,17,0.117647
microrefact/jpetstore-6/manual/2,microrefact,jpetstore-6,manual,2,True,14,155,159,1,17,9 of 11 (81.8%),8 of 20 (40.0%),9,11,0.818182,8,20,0.400000
microrefact/spring-petclinic/manual/0,microrefact,spring-petclinic,manual,0,True,6,1858,1870,22,32,2 of 8 (25.0%),17 of 24 (70.8%),2,8,0.250000,17,24,0.708333
microrefact/spring-petclinic/manual/1,microrefact,spring-petclinic,manual,1,True,6,1312,1262,20,32,4 of 8 (50.0%),16 of 23 (69.6%),4,8,0.500000,16,23,0.695652
microrefact/spring-petclinic/manual/2,microrefact,spring-petclinic,manual,2,True,5,903,911,14,24,4 of 6 (66.7%),11 of 14 (78.6%),4,6,0.666667,11,14,0.785714
microrefact/spring-petclinic/excluding_bloated_commits/0,microrefact,spring-petclinic,excluding_bloated_commits,0,True,4,1858,230,22,32,1 of 8 (12.5%),3 of 24 (12.5%),1,8,0.125000,3,24,0.125000
microrefact/spring-petclinic/excluding_bloated_commits/1,microrefact,spring-petclinic,excluding_bloated_commits,1,True,4,1312,310,20,32,2 of 8 (25.0%),3 of 23 (13.0%),2,8,0.250000,3,23,0.130435
microrefact/spring-petclinic/excluding_bloated_commits/2,microrefact,spring-petclinic,excluding_bloated_commits,2,True,3,903,333,14,24,2 of 6 (33.3%),3 of 14 (21.4%),2,6,0.333333,3,14,0.214286

In [17]:
single_run_metrics = metrics_df[metrics_df.run_name=="manual"].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
metrics_without_bloat = metrics_df[(metrics_df.run_name=="excluding_bloated_commits")|(metrics_df.app!="spring-petclinic")].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
overall_row = get_overall_row(single_run_metrics)
single_run_metrics = pd.concat([single_run_metrics, overall_row.to_frame().T], axis=0)
# format the table for latex
single_run_metrics[["commit_count", "TLOC", "GFC"]] = single_run_metrics[["commit_count", "TLOC", "GFC"]].astype(int)
# single_run_metrics.drop(columns=['new_relevant_artifacts_updated', 'all_new_relevant_artifacts', 'GAR-R',
#        'old_relevant_artifacts_updated', 'all_old_relevant_artifacts',
#        'MAR-R'])
single_run_metrics = single_run_metrics.rename(columns={
    'success_rate': 'Success Rate',
    'commit_count': 'Commit Count',
    'GLOC': 'GLOC',
    'TLOC': 'TLOC',
    'GFC': 'GFC',
    'GAR': 'GAR',
    'MAR': 'MAR'
})
single_run_metrics = single_run_metrics[['app', 'microservice', 'Success Rate', 'Commit Count', 'GLOC', 'TLOC', 'GFC', 'GAR', 'MAR']]
single_run_metrics = single_run_metrics.reset_index(drop=True)
single_run_metrics.replace(
    {
        'app': {
            'spring-petclinic': 'PetClinic',
            'jpetstore-6': 'JPetStore',
            '7ep-demo': '7ep Demo',
        }
    },
    inplace=True
)
single_run_metrics["microservice"] = single_run_metrics["microservice"].apply(lambda x: x.title())
single_run_metrics = single_run_metrics.rename(columns={'microservice': 'Microservice', 'app': 'Application'})
single_run_metrics = single_run_metrics.set_index(['Application', 'Microservice'])
single_run_metrics["Success Rate"] = single_run_metrics["Success Rate"].apply(lambda x: f"{int(x*100)}\\%")
single_run_metrics = single_run_metrics.style.format({
    # 'Success Rate': '{:.1%}',
    'Commit Count': '{:,.0f}',
    'GLOC': '{:,.0f}',
    'TLOC': '{:,.0f}',
    'GFC': '{:,.0f}',
    'GAR': lambda x: x.replace('%', '\\%'),
    'MAR': lambda x: x.replace('%', '\\%'),
})
single_run_metrics

In [ ]:
app_order = ['PetClinic', 'JPetStore', '7ep Demo']

In [30]:
single_run_metrics.sort_values(['Application', 'Microservice'], )

                         Success Rate  Commit Count    GLOC  TLOC  GFC  \
Application Microservice
7ep Demo    0                   100\%             7    1942  1944   17
            1                   100\%             8    3348  3348   24
            2                   100\%             6     760   760   15
            3                   100\%             4    1358  1358   11
JPetStore   0                   100\%             6      58    62    6
            1                   100\%             6      69    69    9
            2                   100\%            14     155   159   17
Overall     Overall             100\%             6  1107.5  1086   17
PetClinic   0                   100\%             6    1858  1870   32
            1                   100\%             6    1312  1262   32
            2                   100\%             5     903   911   24

                                       GAR                 MAR
Application Microservice
7ep Demo    0               1 of 3 (33.3%)    16 of 36 (44.4%)
            1               1 of 7 (14.3%)    19 of 40 (47.5%)
            2                0 of 6 (0.0%)    12 of 24 (50.0%)
            3                0 of 2 (0.0%)    10 of 21 (47.6%)
JPetStore   0               3 of 5 (60.0%)     3 of 10 (30.0%)
            1               7 of 8 (87.5%)     2 of 17 (11.8%)
            2              9 of 11 (81.8%)     8 of 20 (40.0%)
Overall     Overall       31 of 64 (41.9%)  114 of 229 (49.0%)
PetClinic   0               2 of 8 (25.0%)    17 of 24 (70.8%)
            1               4 of 8 (50.0%)    16 of 23 (69.6%)
            2               4 of 6 (66.7%)    11 of 14 (78.6%)

In [23]:
metrics_without_bloat = metrics_df[(metrics_df.run_name=="excluding_bloated_commits")|(metrics_df.app!="spring-petclinic")].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
overall_row_without_bloat = get_overall_row(metrics_without_bloat)
overall_row_without_bloat.app = "Overall*"
overall_row_without_bloat.microservice = "Overall*"
overall_row_without_bloat

app                                        Overall*
microservice                               Overall*
success_rate                                    1.0
commit_count                                    6.0
GLOC                                         1107.5
TLOC                                          321.5
GFC                                            17.0
GAR                                26 of 64 (34.8%)
MAR                               79 of 229 (31.8%)
new_relevant_artifacts_updated                   26
all_new_relevant_artifacts                       64
GAR-R                                      0.347771
old_relevant_artifacts_updated                   79
all_old_relevant_artifacts                      229
MAR-R                                        0.3183
dtype: object

In [21]:
metrics_without_bloat.app = metrics_without_bloat.app.apply(lambda x: "petclinic_without_bloat" if x=="spring-petclinic" else x)

In [5]:
microservice_id_name_map = {
    "7ep-demo": {
        "0": "authentication",
        "1": "library",
        "2": "mathematics",
        "3": "persistence",
    },
    "jpetstore-6": {
        "0": "account",
        "1": "catalog",
        "2": "order",
    },
    "spring-petclinic": {
        "0": "customers",
        "1": "vets",
        "2": "visits",
    }
}

In [25]:
single_run_metrics = metrics_df[metrics_df.run_name=="manual"].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
metrics_without_bloat = metrics_df[(metrics_df.run_name=="excluding_bloated_commits")|(metrics_df.app!="spring-petclinic")].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
overall_row = get_overall_row(single_run_metrics)
overall_row_without_bloat = get_overall_row(metrics_without_bloat)
overall_row_without_bloat.app = "Overall*"
overall_row_without_bloat.microservice = "Overall*"
metrics_without_bloat.app = metrics_without_bloat.app.apply(lambda x: 'spring-petclinic-without-bloat' if x=="spring-petclinic" else x)
single_run_metrics = pd.concat([single_run_metrics, overall_row.to_frame().T, metrics_without_bloat[metrics_without_bloat.app=='spring-petclinic-without-bloat'], overall_row_without_bloat.to_frame().T], axis=0)
# format the table for latex
single_run_metrics[["commit_count", "TLOC", "GFC"]] = single_run_metrics[["commit_count", "TLOC", "GFC"]].astype(int)
# single_run_metrics.drop(columns=['new_relevant_artifacts_updated', 'all_new_relevant_artifacts', 'GAR-R',
#        'old_relevant_artifacts_updated', 'all_old_relevant_artifacts',
#        'MAR-R'])
single_run_metrics = single_run_metrics.rename(columns={
    'success_rate': 'Success Rate',
    'commit_count': 'Commit Count',
    'GLOC': 'GLOC',
    'TLOC': 'TLOC',
    'GFC': 'GFC',
    'GAR': 'GAR',
    'MAR': 'MAR'
})
single_run_metrics = single_run_metrics[['app', 'microservice', 'Commit Count', 'GLOC', 'TLOC', 'GFC', 'GAR', 'MAR']]
single_run_metrics = single_run_metrics.reset_index(drop=True)
single_run_metrics.replace(
    {
        'app': {
            'spring-petclinic-without-bloat': 'PetClinic*',
            'spring-petclinic': 'PetClinic',
            'jpetstore-6': 'JPetStore',
            '7ep-demo': '7ep Demo',
        }
    },
    inplace=True
)
single_run_metrics["microservice"] = single_run_metrics["microservice"].apply(lambda x: x.title())
single_run_metrics = single_run_metrics.rename(columns={'microservice': 'Microservice', 'app': 'Application'})
single_run_metrics = single_run_metrics.set_index(['Application', 'Microservice'])
# single_run_metrics["Success Rate"] = single_run_metrics["Success Rate"].apply(lambda x: f"{int(x*100)}\\%")
single_run_metrics = single_run_metrics.style.format({
    # 'Success Rate': '{:.1%}',
    'Commit Count': '{:,.0f}',
    'GLOC': '{:,.0f}',
    'TLOC': '{:,.0f}',
    'GFC': '{:,.0f}',
    'GAR': lambda x: x.replace('%', '\\%'),
    'MAR': lambda x: x.replace('%', '\\%'),
})
single_run_metrics

In [11]:
single_run_metrics = metrics_df[metrics_df.run_name=="manual"].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
metrics_without_bloat = metrics_df[(metrics_df.run_name=="excluding_bloated_commits")|(metrics_df.app!="spring-petclinic")].reset_index().drop(columns=["key", "benchmark", "run_name", "GHC"])
overall_row = get_overall_row(single_run_metrics)
overall_row_without_bloat = get_overall_row(metrics_without_bloat)
overall_row_without_bloat.app = "Overall*"
overall_row_without_bloat.microservice = "Overall*"
metrics_without_bloat.app = metrics_without_bloat.app.apply(lambda x: 'spring-petclinic-without-bloat' if x=="spring-petclinic" else x)
single_run_metrics = pd.concat([single_run_metrics, overall_row.to_frame().T, metrics_without_bloat[metrics_without_bloat.app=='spring-petclinic-without-bloat'], overall_row_without_bloat.to_frame().T], axis=0)
# format the table for latex
single_run_metrics[["commit_count", "TLOC", "GFC"]] = single_run_metrics[["commit_count", "TLOC", "GFC"]].astype(int)
# single_run_metrics.drop(columns=['new_relevant_artifacts_updated', 'all_new_relevant_artifacts', 'GAR-R',
#        'old_relevant_artifacts_updated', 'all_old_relevant_artifacts',
#        'MAR-R'])
single_run_metrics = single_run_metrics.rename(columns={
    'success_rate': 'Success Rate',
    'commit_count': 'Commit Count',
    'GLOC': 'GLOC',
    'TLOC': 'TLOC',
    'GFC': 'GFC',
    'GAR': 'GAR',
    'MAR': 'MAR'
})
def map_ms_name(row):
    if row["microservice"].startswith("Overall"):
        return row["microservice"]
    elif row["app"] == "spring-petclinic-without-bloat":
        return microservice_id_name_map["spring-petclinic"][row["microservice"]]+"*"
    else:
        return microservice_id_name_map[row["app"]][row["microservice"]]
single_run_metrics["microservice"] = single_run_metrics.apply(map_ms_name, axis=1)
single_run_metrics = single_run_metrics[['app', 'microservice', 'Commit Count', 'GLOC', 'TLOC', 'GFC', 'GAR', 'MAR']]
single_run_metrics = single_run_metrics.reset_index(drop=True)
single_run_metrics.replace(
    {
        'app': {
            'spring-petclinic-without-bloat': 'PetClinic*',
            'spring-petclinic': 'PetClinic',
            'jpetstore-6': 'JPetStore',
            '7ep-demo': '7ep Demo',
        }
    },
    inplace=True
)
single_run_metrics["microservice"] = single_run_metrics["microservice"].apply(lambda x: x.title())
single_run_metrics = single_run_metrics.rename(columns={'microservice': 'Microservice', 'app': 'Application'})
single_run_metrics = single_run_metrics.set_index(['Application', 'Microservice'])
# single_run_metrics["Success Rate"] = single_run_metrics["Success Rate"].apply(lambda x: f"{int(x*100)}\\%")
single_run_metrics = single_run_metrics.style.format({
    # 'Success Rate': '{:.1%}',
    'Commit Count': '{:,.0f}',
    'GLOC': '{:,.0f}',
    'TLOC': '{:,.0f}',
    'GFC': '{:,.0f}',
    'GAR': lambda x: x.replace('%', '\\%'),
    'MAR': lambda x: x.replace('%', '\\%'),
})
single_run_metrics

In [12]:
single_run_metrics_latex_str = single_run_metrics.to_latex(
    hrules=True,
    label="tab-mm:microrefact_rq2_results",
    caption="MicroRefact Effort Metrics",
    position="htbp",
    column_format="ll|cccccccc",
)
print(single_run_metrics_latex_str)

\begin{table}[htbp]
\caption{MicroRefact Effort Metrics}
\label{tab-mm:microrefact_rq2_results}
\begin{tabular}{ll|cccccccc}
\toprule
 &  & Commit Count & GLOC & TLOC & GFC & GAR & MAR \\
Application & Microservice &  &  &  &  &  &  \\
\midrule
\multirow[c]{4}{*}{7ep Demo} & Authentication & 7 & 1,942 & 1,944 & 17 & 1 of 3 (33.3\%) & 16 of 36 (44.4\%) \\
 & Library & 8 & 3,348 & 3,348 & 24 & 1 of 7 (14.3\%) & 19 of 40 (47.5\%) \\
 & Mathematics & 6 & 760 & 760 & 15 & 0 of 6 (0.0\%) & 12 of 24 (50.0\%) \\
 & Persistence & 4 & 1,358 & 1,358 & 11 & 0 of 2 (0.0\%) & 10 of 21 (47.6\%) \\
\multirow[c]{3}{*}{JPetStore} & Account & 6 & 58 & 62 & 6 & 3 of 5 (60.0\%) & 3 of 10 (30.0\%) \\
 & Catalog & 6 & 69 & 69 & 9 & 7 of 8 (87.5\%) & 2 of 17 (11.8\%) \\
 & Order & 14 & 155 & 159 & 17 & 9 of 11 (81.8\%) & 8 of 20 (40.0\%) \\
\multirow[c]{3}{*}{PetClinic} & Customers & 6 & 1,858 & 1,870 & 32 & 2 of 8 (25.0\%) & 17 of 24 (70.8\%) \\
 & Vets & 6 & 1,312 & 1,262 & 32 & 4 of 8 (50.0\%) & 16 of 23 (69.6\%) \\
 & Visits & 5 & 903 & 911 & 24 & 4 of 6 (66.7\%) & 11 of 14 (78.6\%) \\
Overall & Overall & 6 & 1,108 & 1,086 & 17 & 31 of 64 (41.9\%) & 114 of 229 (49.0\%) \\
\multirow[c]{3}{*}{PetClinic*} & Customers* & 4 & 1,858 & 230 & 32 & 1 of 8 (12.5\%) & 3 of 24 (12.5\%) \\
 & Vets* & 4 & 1,312 & 310 & 32 & 2 of 8 (25.0\%) & 3 of 23 (13.0\%) \\
 & Visits* & 3 & 903 & 333 & 24 & 2 of 6 (33.3\%) & 3 of 14 (21.4\%) \\
Overall* & Overall* & 6 & 1,108 & 321 & 17 & 26 of 64 (34.8\%) & 79 of 229 (31.8\%) \\
\bottomrule
\end{tabular}
\end{table}