In [8]:
import logging

logging.basicConfig(level=logging.DEBUG)

## Microservices

In [3]:
monomorph_results = {
    ("microrefact", "7ep-demo", "manual"): {
        "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_important/7ep-demo/run2/7ep-demo-2508061819-bce4",
    },
    ("microrefact", "jpetstore-6", "manual"): {
        "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_important_bck/jpetstore-6/run2/jpetstore-6-2507232035-7d27",
    },
    ("microrefact", "spring-petclinic", "manual"): {
        "path": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_important/spring-petclinic/run2/spring-petclinic-2507231543-0147",
    },
}

In [17]:
import shutil, os

buildable_versions = {
    "7ep-demo": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_important/7ep-demo/run2/7ep-demo-2508061819-bce4",
    "jpetstore-6": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_important_bck/jpetstore-6/run2/jpetstore-6-2507232035-7d27",
    "spring-petclinic": "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data_important/spring-petclinic/run2/spring-petclinic-2507231543-0147",
}

microservices_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices"
microservices_to_modify_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles"
monoliths_with_dockerfiles_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/monoliths-with-dockerfiles"
reports_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports"

In [22]:
for app in buildable_versions:
    print(f"Processing {app}...")
    app_path = buildable_versions[app]
    target_app_path1 = f"{microservices_path}/{app}"
    if not os.path.exists(target_app_path1):
        os.makedirs(microservices_to_modify_path, exist_ok=True)
        shutil.copytree(app_path, target_app_path1)
        print(f"Copied {app} microservices to {target_app_path1}")
    else:
        print(f"{app} microservices already exist at {target_app_path1}")
    target_app_path2 = f"{microservices_to_modify_path}/{app}"
    if not os.path.exists(target_app_path2):
        shutil.copytree(app_path, target_app_path2)
        print(f"Copied {app} microservices to {target_app_path2}")
    else:
        print(f"{app} microservices already exist at {target_app_path2}")
    # Remove the debugging directory if it exists
    debugging_path = f"{target_app_path2}/debugging"
    if os.path.exists(debugging_path):
        shutil.rmtree(debugging_path)
        print(f"Removed debugging directory at {debugging_path}")
    else:
        print(f"No debugging directory to remove at {debugging_path}")
    # Copy the Dockerfile to the target path
    source_dockerfile_path = f"{monoliths_with_dockerfiles_path}/{app}/DockerfileMRtesting"
    microservices = [i for i in os.listdir(target_app_path2) if not i.startswith(".") and i!="debugging" and os.path.isdir(os.path.join(target_app_path2, i))]
    for ms in microservices:
        target_dockerfile_path = f"{target_app_path2}/{ms}/DockerfileMRtesting"
        if not os.path.exists(target_dockerfile_path):
            shutil.copy(source_dockerfile_path, target_dockerfile_path)
            print(f"Copied Dockerfile to {target_dockerfile_path}")
        else:
            print(f"Dockerfile already exists at {target_dockerfile_path}")

Processing 7ep-demo...
7ep-demo microservices already exist at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices/7ep-demo
7ep-demo microservices already exist at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/7ep-demo
No debugging directory to remove at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/7ep-demo/debugging
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/7ep-demo/mathematics/DockerfileMRtesting
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/7ep-demo/library/DockerfileMRtesting
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/7ep-demo/persistence/DockerfileMRtesting
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/7ep-demo/authentication/DockerfileMRtesting
Processing jpetstore-6...
jpetstore-6 microservices already exist at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices/jpetstore-6
jpetstore-6 microservices already exist at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/jpetstore-6
No debugging directory to remove at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/jpetstore-6/debugging
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/jpetstore-6/order/DockerfileMRtesting
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/jpetstore-6/catalog/DockerfileMRtesting
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/jpetstore-6/account/DockerfileMRtesting
Processing spring-petclinic...
spring-petclinic microservices already exist at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices/spring-petclinic
spring-petclinic microservices already exist at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/spring-petclinic
No debugging directory to remove at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/spring-petclinic/debugging
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/spring-petclinic/customers/DockerfileMRtesting
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/spring-petclinic/visits/DockerfileMRtesting
Copied Dockerfile to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microservices-with-dockerfiles/spring-petclinic/vets/DockerfileMRtesting

In [1]:
microservice_id_name_map = {
    "7ep-demo": {
        "0": "authentication",
        "1": "library",
        "2": "mathematics",
        "3": "persistence",
    },
    "jpetstore-6": {
        "0": "account",
        "1": "catalog",
        "2": "order",
    },
    "spring-petclinic": {
        "0": "customers",
        "1": "vets",
        "2": "visits",
    }
}

In [2]:
from pathlib import Path
import shutil
import os

from refacteval.testing.docker import test_microservice_with_compose

microservices_to_modify_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microrefact"
reports_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports"

In [29]:
app = "7ep-demo" #"spring-petclinic"#"jpetstore-6" #
server_services = ["authentication"]
ms_app_path = f"{microservices_to_modify_path}/{app}"
microservices = [i for i in os.listdir(ms_app_path) if not i.startswith(".") and i!="debugging" and os.path.isdir(os.path.join(ms_app_path, i))]
print(microservices)

['0', '1', '3', '2']

In [30]:
import re

defined_server_pattern = re.compile(r"\s*([a-zA-Z0-9_-]+-server):\s*")

docker_compose_file = f"{ms_app_path}/docker-compose.yml"

assert os.path.exists(docker_compose_file)

with open(docker_compose_file, "r") as f:
    docker_compose_content = f.read()

defined_server_services = list(set(defined_server_pattern.findall(docker_compose_content)))
defined_server_services

[]

In [32]:
from subprocess import CalledProcessError

for ms in microservices:
    print(f"Testing {ms}...")
    ms_path = f"{ms_app_path}/{ms}"
    ms_report_path = Path(f"{reports_path}/microrefact/{app}")
    if (ms_report_path/ms).exists():
        print(f"Report for {ms} already exists at {ms_report_path/ms}")
        continue
    else:
        print(f"Creating report directory for {ms} at {ms_report_path/ms}")
    if not os.path.exists(ms_report_path):
        os.makedirs(ms_report_path, exist_ok=True)
    build_tool = "gradle" if app=="7ep-demo" else "maven"
    try:
        test_microservice_with_compose(ms, defined_server_services, Path(ms_app_path), ms_report_path, build_tool, True, True,
                                       test_runner_service=f"{microservice_id_name_map[app][ms]}-tests")
    except CalledProcessError as e:
        print(f"Testing {ms} failed with error: {e}")
        continue

INFO:refacteval:--- Starting test run for microservice: 1 ---
INFO:refacteval:Working directory: /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microrefact/7ep-demo
INFO:refacteval:Reports will be saved to: /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/1
INFO:refacteval:No server services to start.
INFO:refacteval:Running test container for service: 'library-tests'

Testing 0...
Report for 0 already exists at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/0
Testing 1...
Creating report directory for 1 at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/1

time="2025-12-08T16:52:59-05:00" level=warning msg="/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microrefact/7ep-demo/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 Network 7ep-demo_testing_network  Creating
 Network 7ep-demo_testing_network  Created
time="2025-12-08T16:53:00-05:00" level=warning msg="Found orphan containers ([authentication-tests-cont-1765230554]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."

#1 [internal] load local bake definitions
#1 reading from stdin 709B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.15kB done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/gradle:7.4.2-jdk11-jammy
#3 DONE 0.0s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [build 1/9] FROM docker.io/library/gradle:7.4.2-jdk11-jammy
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 290.15kB 0.0s done
#6 DONE 0.0s

#7 [build 3/9] COPY build.gradle settings.gradle* ./
#7 CACHED

#8 [build 2/9] WORKDIR /app
#8 CACHED

#9 [build 4/9] COPY gradle ./gradle
#9 CACHED

#10 [build 5/9] COPY gradle* ./
#10 CACHED

#11 [build 6/9] COPY src/main/webapp ./src/main/webapp
#11 CACHED

#12 [build 7/9] RUN gradle dependencies --no-daemon
#12 0.445
#12 0.445 Welcome to Gradle 7.4.2!
#12 0.445
#12 0.445 Here are the highlights of this release:
#12 0.445  - Aggregated test and JaCoCo reports
#12 0.445  - Marking additional test source directories as tests in IntelliJ
#12 0.445  - Support for Adoptium JDKs in Java toolchains
#12 0.445
#12 0.445 For more details see https://docs.gradle.org/7.4.2/release-notes.html
#12 0.445
#12 0.446 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
#12 0.941 Daemon will be stopped at the end of the build
#12 56.44
#12 56.44 > Task :dependencies
#12 56.44
#12 56.44 ------------------------------------------------------------
#12 56.44 Root project 'app' - A demonstration of a web application with CI/CD
#12 56.44 ------------------------------------------------------------
#12 56.44
#12 56.44 annotationProcessor - Annotation processors and their dependencies for source set 'main'.
#12 56.44 No dependencies
#12 56.44
#12 56.44 api - API dependencies for source set 'main'. (n)
#12 56.44 No dependencies
#12 56.44
#12 56.44 apiElements - API elements for main. (n)
#12 56.44 No dependencies
#12 56.44
#12 56.44 archives - Configuration for archive artifacts. (n)
#12 56.44 No dependencies
#12 56.44
#12 56.44 bootArchives - Configuration for Spring Boot archive artifacts. (n)
#12 56.44 No dependencies
#12 56.44
#12 56.44 checkerFramework - A copy of JDK classes with Checker Framework type qualifiers inserted.
#12 56.44 \--- org.checkerframework:checker:3.3.0
#12 56.44
#12 56.44 checkerFrameworkAnnotatedJDK - A copy of JDK classes with Checker Framework type qualifiers inserted.
#12 56.44 \--- org.checkerframework:jdk8:3.3.0
#12 56.44
#12 56.44 compileClasspath - Compile classpath for source set 'main'.
#12 75.44 +--- org.checkerframework:checker-qual:3.3.0
#12 75.44 +--- javax.servlet:javax.servlet-api:4.0.1
#12 75.44 +--- org.springframework.boot:spring-boot-starter-cache -> 2.7.18
#12 75.44 |    +--- org.springframework.boot:spring-boot-starter:2.7.18
#12 75.44 |    |    +--- org.springframework.boot:spring-boot:2.7.18
#12 75.44 |    |    |    +--- org.springframework:spring-core:5.3.31
#12 75.44 |    |    |    |    \--- org.springframework:spring-jcl:5.3.31
#12 75.44 |    |    |    \--- org.springframework:spring-context:5.3.31
#12 75.44 |    |    |         +--- org.springframework:spring-aop:5.3.31
#12 75.44 |    |    |         |    +--- org.springframework:spring-beans:5.3.31
#12 75.44 |    |    |         |    |    \--- org.springframework:spring-core:5.3.31 (*)
#12 75.44 |    |    |         |    \--- org.springframework:spring-core:5.3.31 (*)
#12 75.44 |    |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.44 |    |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 75.54 |    |    |         \--- org.springframework:spring-expression:5.3.31
#12 75.54 |    |    |              \--- org.springframework:spring-core:5.3.31 (*)
#12 75.54 |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.7.18
#12 75.54 |    |    |    \--- org.springframework.boot:spring-boot:2.7.18 (*)
#12 75.54 |    |    +--- org.springframework.boot:spring-boot-starter-logging:2.7.18
#12 75.54 |    |    |    +--- ch.qos.logback:logback-classic:1.2.12
#12 75.54 |    |    |    |    +--- ch.qos.logback:logback-core:1.2.12
#12 75.54 |    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 75.55 |    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.17.2
#12 75.55 |    |    |    |    +--- org.slf4j:slf4j-api:1.7.35 -> 1.7.36
#12 75.55 |    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.17.2 -> 2.13.2
#12 75.55 |    |    |    \--- org.slf4j:jul-to-slf4j:1.7.36
#12 75.55 |    |    |         \--- org.slf4j:slf4j-api:1.7.36
#12 75.55 |    |    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
#12 75.55 |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |    |    \--- org.yaml:snakeyaml:1.30
#12 75.55 |    \--- org.springframework:spring-context-support:5.3.31
#12 75.55 |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |         +--- org.springframework:spring-context:5.3.31 (*)
#12 75.55 |         \--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 +--- org.springframework.boot:spring-boot-starter-data-jpa -> 2.7.18
#12 75.55 |    +--- org.springframework.boot:spring-boot-starter-aop:2.7.18
#12 75.55 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 75.55 |    |    +--- org.springframework:spring-aop:5.3.31 (*)
#12 75.55 |    |    \--- org.aspectj:aspectjweaver:1.9.7
#12 75.55 |    +--- org.springframework.boot:spring-boot-starter-jdbc:2.7.18
#12 75.55 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 75.55 |    |    +--- com.zaxxer:HikariCP:4.0.3
#12 75.55 |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
#12 75.55 |    |    \--- org.springframework:spring-jdbc:5.3.31
#12 75.55 |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |    |         \--- org.springframework:spring-tx:5.3.31
#12 75.55 |    |              +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |    |              \--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |    +--- jakarta.transaction:jakarta.transaction-api:1.3.3
#12 75.55 |    +--- jakarta.persistence:jakarta.persistence-api:2.2.3
#12 75.55 |    +--- org.hibernate:hibernate-core:5.6.15.Final
#12 75.55 |    |    +--- org.jboss.logging:jboss-logging:3.4.3.Final
#12 75.55 |    |    +--- net.bytebuddy:byte-buddy:1.12.18 -> 1.12.23
#12 75.55 |    |    +--- antlr:antlr:2.7.7
#12 75.55 |    |    +--- org.jboss:jandex:2.4.2.Final
#12 75.55 |    |    +--- com.fasterxml:classmate:1.5.1
#12 75.55 |    |    +--- org.hibernate.common:hibernate-commons-annotations:5.1.2.Final
#12 75.55 |    |    |    \--- org.jboss.logging:jboss-logging:3.3.2.Final -> 3.4.3.Final
#12 75.55 |    |    \--- org.glassfish.jaxb:jaxb-runtime:2.3.1 -> 2.3.9
#12 75.55 |    |         +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.3
#12 75.55 |    |         |    \--- jakarta.activation:jakarta.activation-api:1.2.2
#12 75.55 |    |         +--- org.glassfish.jaxb:txw2:2.3.9
#12 75.55 |    |         \--- com.sun.istack:istack-commons-runtime:3.0.12
#12 75.55 |    +--- org.springframework.data:spring-data-jpa:2.7.18
#12 75.55 |    |    +--- org.springframework.data:spring-data-commons:2.7.18
#12 75.55 |    |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |    |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 75.55 |    |    +--- org.springframework:spring-orm:5.3.31
#12 75.55 |    |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |    |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |    |    |    +--- org.springframework:spring-jdbc:5.3.31 (*)
#12 75.55 |    |    |    \--- org.springframework:spring-tx:5.3.31 (*)
#12 75.55 |    |    +--- org.springframework:spring-context:5.3.31 (*)
#12 75.55 |    |    +--- org.springframework:spring-aop:5.3.31 (*)
#12 75.55 |    |    +--- org.springframework:spring-tx:5.3.31 (*)
#12 75.55 |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 75.55 |    \--- org.springframework:spring-aspects:5.3.31
#12 75.55 |         \--- org.aspectj:aspectjweaver:1.9.7
#12 75.55 +--- org.springframework.boot:spring-boot-starter-thymeleaf -> 2.7.18
#12 75.55 |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 75.55 |    +--- org.thymeleaf:thymeleaf-spring5:3.0.15.RELEASE
#12 75.55 |    |    +--- org.thymeleaf:thymeleaf:3.0.15.RELEASE
#12 75.55 |    |    |    +--- org.attoparser:attoparser:2.0.5.RELEASE
#12 75.55 |    |    |    +--- org.unbescape:unbescape:1.1.6.RELEASE
#12 75.55 |    |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 75.55 |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 75.55 |    \--- org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE
#12 75.55 |         +--- org.thymeleaf:thymeleaf:3.0.11.RELEASE -> 3.0.15.RELEASE (*)
#12 75.55 |         \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 75.55 +--- org.springframework.boot:spring-boot-starter-web -> 2.7.18
#12 75.55 |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 75.55 |    +--- org.springframework.boot:spring-boot-starter-json:2.7.18
#12 75.55 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 75.55 |    |    +--- org.springframework:spring-web:5.3.31
#12 75.55 |    |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |    |    |    \--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.5
#12 75.55 |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.5
#12 75.55 |    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5
#12 75.55 |    |    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.13.5 (c)
#12 75.55 |    |    |    |         +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (c)
#12 75.55 |    |    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (c)
#12 75.55 |    |    |    |         +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.5 (c)
#12 75.55 |    |    |    |         +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.5 (c)
#12 75.55 |    |    |    |         \--- com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.5 (c)
#12 75.55 |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.5
#12 75.55 |    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 75.55 |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 75.55 |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.5
#12 75.55 |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (*)
#12 75.55 |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (*)
#12 75.55 |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 75.55 |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.5
#12 75.55 |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.5 (*)
#12 75.55 |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (*)
#12 75.55 |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (*)
#12 75.55 |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 75.55 |    |    \--- com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.5
#12 75.55 |    |         +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (*)
#12 75.55 |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (*)
#12 75.55 |    |         \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 75.55 |    +--- org.springframework:spring-web:5.3.31 (*)
#12 75.55 |    \--- org.springframework:spring-webmvc:5.3.31
#12 75.55 |         +--- org.springframework:spring-aop:5.3.31 (*)
#12 75.55 |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 75.55 |         +--- org.springframework:spring-context:5.3.31 (*)
#12 75.55 |         +--- org.springframework:spring-core:5.3.31 (*)
#12 75.55 |         +--- org.springframework:spring-expression:5.3.31 (*)
#12 75.55 |         \--- org.springframework:spring-web:5.3.31 (*)
#12 75.55 +--- org.springframework.boot:spring-boot-starter-validation -> 2.7.18
#12 75.55 |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 75.55 |    +--- org.apache.tomcat.embed:tomcat-embed-el:9.0.83
#12 75.55 |    \--- org.hibernate.validator:hibernate-validator:6.2.5.Final
#12 75.55 |         +--- jakarta.validation:jakarta.validation-api:2.0.2
#12 75.55 |         +--- org.jboss.logging:jboss-logging:3.4.1.Final -> 3.4.3.Final
#12 75.55 |         \--- com.fasterxml:classmate:1.5.1
#12 75.55 +--- javax.cache:cache-api -> 1.1.1
#12 75.55 +--- jakarta.xml.bind:jakarta.xml.bind-api -> 2.3.3 (*)
#12 75.55 +--- junit:junit:4.13
#12 75.55 |    \--- org.hamcrest:hamcrest-core:1.3 -> 2.2
#12 75.55 |         \--- org.hamcrest:hamcrest:2.2
#12 75.55 +--- org.mockito:mockito-core:3.3.3
#12 75.55 |    +--- net.bytebuddy:byte-buddy:1.10.5 -> 1.12.23
#12 75.55 |    +--- net.bytebuddy:byte-buddy-agent:1.10.5 -> 1.12.23
#12 75.55 |    \--- org.objenesis:objenesis:2.6
#12 75.55 +--- me.gosimple:nbvcxz:1.4.3
#12 75.55 +--- nl.jqno.equalsverifier:equalsverifier:3.1.13
#12 75.55 +--- io.cucumber:cucumber-java:5.7.0
#12 75.55 |    +--- io.cucumber:cucumber-core:5.7.0
#12 75.55 |    |    +--- io.cucumber:cucumber-gherkin:5.7.0
#12 75.55 |    |    |    \--- io.cucumber:cucumber-plugin:5.7.0
#12 75.55 |    |    |         \--- org.apiguardian:apiguardian-api:1.1.0
#12 75.55 |    |    +--- io.cucumber:cucumber-gherkin-vintage:5.7.0
#12 75.55 |    |    |    \--- io.cucumber:cucumber-gherkin:5.7.0 (*)
#12 75.55 |    |    +--- io.cucumber:tag-expressions:2.0.4
#12 75.55 |    |    +--- io.cucumber:cucumber-expressions:8.3.1
#12 75.55 |    |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 75.55 |    |    +--- io.cucumber:datatable:3.3.1
#12 75.55 |    |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 75.55 |    |    +--- io.cucumber:cucumber-plugin:5.7.0 (*)
#12 75.55 |    |    +--- io.cucumber:docstring:5.7.0
#12 75.55 |    |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 75.55 |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 75.55 |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 75.55 +--- io.cucumber:cucumber-junit:5.7.0
#12 75.55 |    +--- org.apiguardian:apiguardian-api:1.1.0
#12 75.55 |    +--- io.cucumber:cucumber-core:5.7.0 (*)
#12 75.55 |    \--- junit:junit:4.13 (*)
#12 75.55 +--- org.apache.commons:commons-lang3:3.10
#12 75.55 +--- org.apache.logging.log4j:log4j-api:2.13.2
#12 75.55 +--- org.apache.logging.log4j:log4j-core:2.13.2
#12 75.55 |    \--- org.apache.logging.log4j:log4j-api:2.13.2
#12 75.55 +--- org.apache.logging.log4j:log4j-slf4j-impl:2.13.2
#12 75.55 |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 75.55 |    \--- org.apache.logging.log4j:log4j-api:2.13.2
#12 75.55 +--- org.flywaydb:flyway-core:6.4.1
#12 75.55 +--- net.bull.javamelody:javamelody-core:1.85.0
#12 75.55 |    \--- org.jrobin:jrobin:1.5.9
#12 75.55 \--- com.h2database:h2:1.4.200
#12 75.55
#12 75.55 compileOnly - Compile only dependencies for source set 'main'. (n)
#12 75.55 \--- org.checkerframework:checker-qual:3.3.0 (n)
#12 75.55
#12 75.55 compileOnlyApi - Compile only API dependencies for source set 'main'. (n)
#12 75.55 No dependencies
#12 75.55
#12 75.55 coverageDataElementsForTest - Binary data file containing results of Jacoco test coverage reporting for the test Test Suite's test target. (n)
#12 75.55 No dependencies
#12 75.55
#12 75.55 cucumberBddTestAnnotationProcessor - Annotation processors and their dependencies for source set 'cucumber bdd test'.
#12 75.55 No dependencies
#12 75.55
#12 75.55 cucumberBddTestCompileClasspath - Compile classpath for source set 'cucumber bdd test'.
#12 78.94 +--- javax.servlet:javax.servlet-api:4.0.1
#12 78.94 +--- org.springframework.boot:spring-boot-starter-cache -> 2.7.18
#12 78.94 |    +--- org.springframework.boot:spring-boot-starter:2.7.18
#12 78.94 |    |    +--- org.springframework.boot:spring-boot:2.7.18
#12 78.94 |    |    |    +--- org.springframework:spring-core:5.3.31
#12 78.94 |    |    |    |    \--- org.springframework:spring-jcl:5.3.31
#12 78.94 |    |    |    \--- org.springframework:spring-context:5.3.31
#12 78.94 |    |    |         +--- org.springframework:spring-aop:5.3.31
#12 78.94 |    |    |         |    +--- org.springframework:spring-beans:5.3.31
#12 78.94 |    |    |         |    |    \--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 |    |    |         |    \--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 |    |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 78.94 |    |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 |    |    |         \--- org.springframework:spring-expression:5.3.31
#12 78.94 |    |    |              \--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.7.18
#12 78.94 |    |    |    \--- org.springframework.boot:spring-boot:2.7.18 (*)
#12 78.94 |    |    +--- org.springframework.boot:spring-boot-starter-logging:2.7.18
#12 78.94 |    |    |    +--- ch.qos.logback:logback-classic:1.2.12
#12 78.94 |    |    |    |    +--- ch.qos.logback:logback-core:1.2.12
#12 78.94 |    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 78.94 |    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.17.2
#12 78.94 |    |    |    |    +--- org.slf4j:slf4j-api:1.7.35 -> 1.7.36
#12 78.94 |    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.17.2 -> 2.13.2
#12 78.94 |    |    |    \--- org.slf4j:jul-to-slf4j:1.7.36
#12 78.94 |    |    |         \--- org.slf4j:slf4j-api:1.7.36
#12 78.94 |    |    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
#12 78.94 |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 |    |    \--- org.yaml:snakeyaml:1.30
#12 78.94 |    \--- org.springframework:spring-context-support:5.3.31
#12 78.94 |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 78.94 |         +--- org.springframework:spring-context:5.3.31 (*)
#12 78.94 |         \--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 +--- org.springframework.boot:spring-boot-starter-data-jpa -> 2.7.18
#12 78.94 |    +--- org.springframework.boot:spring-boot-starter-aop:2.7.18
#12 78.94 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 78.94 |    |    +--- org.springframework:spring-aop:5.3.31 (*)
#12 78.94 |    |    \--- org.aspectj:aspectjweaver:1.9.7
#12 78.94 |    +--- org.springframework.boot:spring-boot-starter-jdbc:2.7.18
#12 78.94 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 78.94 |    |    +--- com.zaxxer:HikariCP:4.0.3
#12 78.94 |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
#12 78.94 |    |    \--- org.springframework:spring-jdbc:5.3.31
#12 78.94 |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 78.94 |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 |    |         \--- org.springframework:spring-tx:5.3.31
#12 78.94 |    |              +--- org.springframework:spring-beans:5.3.31 (*)
#12 78.94 |    |              \--- org.springframework:spring-core:5.3.31 (*)
#12 78.94 |    +--- jakarta.transaction:jakarta.transaction-api:1.3.3
#12 78.94 |    +--- jakarta.persistence:jakarta.persistence-api:2.2.3
#12 78.94 |    +--- org.hibernate:hibernate-core:5.6.15.Final
#12 78.94 |    |    +--- org.jboss.logging:jboss-logging:3.4.3.Final
#12 78.94 |    |    +--- net.bytebuddy:byte-buddy:1.12.18 -> 1.12.23

Note: /app/src/test/java/com/coveros/training/library/LibraryUtilsTests.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Created classpath snapshot for incremental compilation in 1.098 secs.
:compileTestJava (Thread[included builds,5,main]) completed. Took 2.613 secs.
:processTestResources (Thread[included builds,5,main]) started.

> Task :processTestResources NO-SOURCE
Skipping task ':processTestResources' as it has no source files and no previous output files.
:processTestResources (Thread[included builds,5,main]) completed. Took 0.002 secs.
:testClasses (Thread[included builds,5,main]) started.

> Task :testClasses
Skipping task ':testClasses' as it has no actions.
:testClasses (Thread[included builds,5,main]) completed. Took 0.0 secs.
:test (Thread[included builds,5,main]) started.
Gradle Test Executor 2 started executing tests.
Gradle Test Executor 2 finished executing tests.

> Task :test FAILED
Excluding []
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  No history is available.
:test.maxParallelForks (5) is larger than max-workers (1), forcing it to 1
Starting process 'Gradle Test Executor 2'. Working directory: /app Command: /opt/java/openjdk/bin/java -Dorg.gradle.internal.worker.tmpdir=/app/build/tmp/test/work -Dorg.gradle.native=false -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.7.jar_3a83c50b4a016f281c4e9f3500d16b55/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false @/home/gradle/.gradle/.tmp/gradle-worker-classpath12134402666894080064txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 2'
Successfully started process 'Gradle Test Executor 2'

com.coveros.training.helpers.StringUtilsTests > testEscapeForJson_ShouldEscapeBackslash FAILED
    org.junit.ComparisonFailure: expected:<[  ]> but was:<[\u0000]>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.coveros.training.helpers.StringUtilsTests.testEscapeForJson_ShouldEscapeBackslash(StringUtilsTests.java:41)

com.coveros.training.helpers.StringUtilsTests > testEscapeForJson_ShouldEscapeDoubleQuote FAILED
    org.junit.ComparisonFailure: expected:<[  ]> but was:<[\u0000]>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.coveros.training.helpers.StringUtilsTests.testEscapeForJson_ShouldEscapeDoubleQuote(StringUtilsTests.java:30)

com.coveros.training.library.LendingTests > shouldRegisterBorrower FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.registerBorrower(LibraryUtils.java:30)
        at com.coveros.training.library.LendingTests.shouldRegisterBorrower(LendingTests.java:56)

com.coveros.training.library.LendingTests > testShouldNotLendIfBorrowerNotRegistered FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.lendBook(LibraryUtils.java:256)
        at com.coveros.training.library.LendingTests.testShouldNotLendIfBorrowerNotRegistered(LendingTests.java:93)

com.coveros.training.library.LendingTests > testShouldNotLendIfBookNotRegistered FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.lendBook(LibraryUtils.java:248)
        at com.coveros.training.library.LendingTests.testShouldNotLendIfBookNotRegistered(LendingTests.java:103)

com.coveros.training.library.LendingTests > shouldRegisterBook FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.registerBook(LibraryUtils.java:70)
        at com.coveros.training.library.LendingTests.shouldRegisterBook(LendingTests.java:75)

com.coveros.training.library.LendingTests > shouldLendToUser FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.lendBook(LibraryUtils.java:272)
        at com.coveros.training.library.LendingTests.shouldLendToUser(LendingTests.java:37)

com.coveros.training.library.LendingTests > shouldNotLendIfCurrentlyBorrowed FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.lendBook(LibraryUtils.java:266)
        at com.coveros.training.library.LendingTests.shouldNotLendIfCurrentlyBorrowed(LendingTests.java:114)

com.coveros.training.library.LibraryBookListAvailableServletTests > testListAvailableBooks_OneBook STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/home/gradle/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.13.2/49df25f7a35dd7fbd8131fc5ab09665d18e3d4fe/log4j-slf4j-impl-2.13.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/home/gradle/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.12/d4dee19148dccb177a0736eb2027bd195341da78/logback-classic-1.2.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

com.coveros.training.library.LibraryBookListAvailableServletTests > testListAvailableBooks_OneBook FAILED
    java.lang.ExceptionInInitializerError
        at com.coveros.training.library.LibraryBookListAvailableServletTests.<init>(LibraryBookListAvailableServletTests.java:24)

        Caused by:
        org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.validateContext(Log4jLoggerFactory.java:49)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:30)
            at app//org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:54)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
            at app//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
            at app//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
            at app//com.coveros.training.library.LibraryBookListAvailableServlet.<clinit>(LibraryBookListAvailableServlet.java:19)
            ... 1 more

com.coveros.training.library.LibraryBookListAvailableServletTests > testListAvailableBooks_MultipleBook FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListAvailableServlet
        at com.coveros.training.library.LibraryBookListAvailableServletTests.<init>(LibraryBookListAvailableServletTests.java:24)

com.coveros.training.library.LibraryBookListAvailableServletTests > testSearchNoBooks FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListAvailableServlet
        at com.coveros.training.library.LibraryBookListAvailableServletTests.<init>(LibraryBookListAvailableServletTests.java:24)

com.coveros.training.library.LibraryBookListAvailableServletTests > testListAvailableBooks_EmptyList FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListAvailableServlet
        at com.coveros.training.library.LibraryBookListAvailableServletTests.<init>(LibraryBookListAvailableServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testSearchNothingFoundByTitle FAILED
    java.lang.ExceptionInInitializerError
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

        Caused by:
        org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.validateContext(Log4jLoggerFactory.java:49)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:30)
            at app//org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:54)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
            at app//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
            at app//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
            at app//com.coveros.training.library.LibraryBookListSearchServlet.<clinit>(LibraryBookListSearchServlet.java:20)
            ... 1 more

com.coveros.training.library.LibraryBookListSearchServletTests > testSearchById FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testListAllBooks_NoBooksInDatabase FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testSearchByTitle FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testListAllBooks FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testSearchIdAndTitle FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testSearchNoBooks FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testSearchNothingFoundById FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBookListSearchServletTests > testSearchById_noBookFound FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBookListSearchServlet
        at com.coveros.training.library.LibraryBookListSearchServletTests.<init>(LibraryBookListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchNoBorrowers FAILED
    java.lang.ExceptionInInitializerError
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

        Caused by:
        org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.validateContext(Log4jLoggerFactory.java:49)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:30)
            at app//org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:54)
            at app//org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
            at app//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
            at app//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
            at app//com.coveros.training.library.LibraryBorrowerListSearchServlet.<clinit>(LibraryBorrowerListSearchServlet.java:20)
            ... 1 more

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchByNameNotFound FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchById FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testListAllBorrowers_noBorrowersExist FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testListAllBorrowers FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchByBadId FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchBorrowerFoundById FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchIdAndName FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchNothingFoundByName FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchByName FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryBorrowerListSearchServletTests > testSearchNothingFoundById FAILED
    java.lang.NoClassDefFoundError: Could not initialize class com.coveros.training.library.LibraryBorrowerListSearchServlet
        at com.coveros.training.library.LibraryBorrowerListSearchServletTests.<init>(LibraryBorrowerListSearchServletTests.java:24)

com.coveros.training.library.LibraryLendServletTests > testHappyPathPost FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryLendServlet.doPost(LibraryLendServlet.java:57)
        at com.coveros.training.library.LibraryLendServletTests.testHappyPathPost(LibraryLendServletTests.java:34)

com.coveros.training.library.LibraryRegisterBookServletTests > testHappyPathPost FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryRegisterBookServlet.doPost(LibraryRegisterBookServlet.java:38)
        at com.coveros.training.library.LibraryRegisterBookServletTests.testHappyPathPost(LibraryRegisterBookServletTests.java:39)

com.coveros.training.library.LibraryRegisterBookServletTests > testEmptyString FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryRegisterBookServlet.doPost(LibraryRegisterBookServlet.java:32)
        at com.coveros.training.library.LibraryRegisterBookServletTests.testEmptyString(LibraryRegisterBookServletTests.java:56)

com.coveros.training.library.LibraryRegisterBorrowerServletTests > testHappyPathPost FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryRegisterBorrowerServlet.doPost(LibraryRegisterBorrowerServlet.java:38)
        at com.coveros.training.library.LibraryRegisterBorrowerServletTests.testHappyPathPost(LibraryRegisterBorrowerServletTests.java:38)

com.coveros.training.library.LibraryRegisterBorrowerServletTests > testEmptyString FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryRegisterBorrowerServlet.doPost(LibraryRegisterBorrowerServlet.java:32)
        at com.coveros.training.library.LibraryRegisterBorrowerServletTests.testEmptyString(LibraryRegisterBorrowerServletTests.java:56)

com.coveros.training.library.LibraryUtilsTests > testCanRegisterBorrower FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.registerBorrower(LibraryUtils.java:30)
        at com.coveros.training.library.LibraryUtilsTests.testCanRegisterBorrower(LibraryUtilsTests.java:73)

com.coveros.training.library.LibraryUtilsTests > testCanDeleteBorrower FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.deleteBorrower(LibraryUtils.java:93)
        at com.coveros.training.library.LibraryUtilsTests.testCanDeleteBorrower(LibraryUtilsTests.java:190)

com.coveros.training.library.LibraryUtilsTests > testCanSearchForBooksById FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.searchForBookById(LibraryUtils.java:332)
        at com.coveros.training.library.LibraryUtilsTests.testCanSearchForBooksById(LibraryUtilsTests.java:142)

com.coveros.training.library.LibraryUtilsTests > testCanSearchForLoanByBorrower FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.searchForLoanByBorrower(LibraryUtils.java:116)
        at com.coveros.training.library.LibraryUtilsTests.testCanSearchForLoanByBorrower(LibraryUtilsTests.java:111)

com.coveros.training.library.LibraryUtilsTests > testCannotDeleteNonRegisteredBorrower FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.deleteBorrower(LibraryUtils.java:93)
        at com.coveros.training.library.LibraryUtilsTests.testCannotDeleteNonRegisteredBorrower(LibraryUtilsTests.java:203)

com.coveros.training.library.LibraryUtilsTests > testCanSearchForBorrowerByName FAILED
    java.lang.NullPointerException
        at com.coveros.training.library.LibraryUtils.searchForBorrowerByName(LibraryUtils.java:189)

94 tests completed, 58 failed

> Task :jacocoTestReport
Cached resource https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.pom is up-to-date (lastModified: Sat Feb 06 12:31:13 UTC 2021).
Cached resource https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.pom is up-to-date (lastModified: Sat Feb 06 12:31:19 UTC 2021).
Excluding []
Caching disabled for task ':jacocoTestReport' because:
  Build cache is disabled
Task ':jacocoTestReport' is not up-to-date because:
  No history is available.
[ant:jacocoReport] Loading execution data file /app/build/jacoco/test.exec
[ant:jacocoReport] Writing bundle 'app' with 29 classes
:jacocoTestReport (Thread[included builds,5,main]) completed. Took 0.919 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 3 executed, 2 up-to-date
Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
Created user preferences directory.
Stopped 1 worker daemon(s).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///app/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

ERROR:refacteval:Test run failed for 'library-tests' with exit code 1.
INFO:refacteval:Entering cleanup and report extraction phase...
INFO:refacteval:Gradle test reports copied to /var/folders/rx/vycj7vys6v78_nd6qmwm7nj40000gn/T/tmpue6kg_9t
INFO:refacteval:Output directory /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/1 exists but is empty. Proceeding to copy reports.
INFO:refacteval:Test reports copied to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/1
INFO:refacteval:Tearing down Docker Compose environment...
INFO:refacteval:...and removing images.
INFO:refacteval:Environment torn down successfully.
INFO:refacteval:--- Test run for microservice: 1 finished ---
INFO:refacteval:--- Starting test run for microservice: 3 ---
INFO:refacteval:Working directory: /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microrefact/7ep-demo
INFO:refacteval:Reports will be saved to: /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/3
INFO:refacteval:No server services to start.
INFO:refacteval:Running test container for service: 'persistence-tests'
time="2025-12-08T16:55:10-05:00" level=warning msg="/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microrefact/7ep-demo/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 Network 7ep-demo_testing_network  Creating
 Network 7ep-demo_testing_network  Created
time="2025-12-08T16:55:10-05:00" level=warning msg="Found orphan containers ([library-tests-cont-1765230779 authentication-tests-cont-1765230554]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."

Testing 1 failed with error: Command '['docker-compose', 'run', '--name', 'library-tests-cont-1765230779', 'library-tests']' returned non-zero exit status 1.
Testing 3...
Creating report directory for 3 at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/3
#1 [internal] load local bake definitions
#1 reading from stdin 725B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.15kB done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/gradle:7.4.2-jdk11-jammy
#3 DONE 0.0s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [build 1/9] FROM docker.io/library/gradle:7.4.2-jdk11-jammy
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 4.34kB done
#6 DONE 0.0s

#7 [build 2/9] WORKDIR /app
#7 CACHED

#8 [build 5/9] COPY gradle* ./
#8 CACHED

#9 [build 4/9] COPY gradle ./gradle
#9 CACHED

#10 [build 3/9] COPY build.gradle settings.gradle* ./
#10 CACHED

#11 [build 6/9] COPY src/main/webapp ./src/main/webapp
#11 CACHED

#12 [build 7/9] RUN gradle dependencies --no-daemon
#12 0.392
#12 0.392 Welcome to Gradle 7.4.2!
#12 0.392
#12 0.392 Here are the highlights of this release:
#12 0.392  - Aggregated test and JaCoCo reports
#12 0.393  - Marking additional test source directories as tests in IntelliJ
#12 0.393  - Support for Adoptium JDKs in Java toolchains
#12 0.393
#12 0.393 For more details see https://docs.gradle.org/7.4.2/release-notes.html
#12 0.393
#12 0.393 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
#12 0.888 Daemon will be stopped at the end of the build
#12 48.09
#12 48.09 > Task :dependencies
#12 48.09
#12 48.09 ------------------------------------------------------------
#12 48.09 Root project 'app' - A demonstration of a web application with CI/CD
#12 48.09 ------------------------------------------------------------
#12 48.09
#12 48.09 annotationProcessor - Annotation processors and their dependencies for source set 'main'.
#12 48.09 No dependencies
#12 48.09
#12 48.09 api - API dependencies for source set 'main'. (n)
#12 48.09 No dependencies
#12 48.09
#12 48.09 apiElements - API elements for main. (n)
#12 48.09 No dependencies
#12 48.09
#12 48.09 archives - Configuration for archive artifacts. (n)
#12 48.09 No dependencies
#12 48.09
#12 48.09 bootArchives - Configuration for Spring Boot archive artifacts. (n)
#12 48.09 No dependencies
#12 48.09
#12 48.09 checkerFramework - A copy of JDK classes with Checker Framework type qualifiers inserted.
#12 48.09 \--- org.checkerframework:checker:3.3.0
#12 48.09
#12 48.09 checkerFrameworkAnnotatedJDK - A copy of JDK classes with Checker Framework type qualifiers inserted.
#12 48.09 \--- org.checkerframework:jdk8:3.3.0
#12 48.09
#12 48.09 compileClasspath - Compile classpath for source set 'main'.
#12 62.29 +--- org.checkerframework:checker-qual:3.3.0
#12 62.29 +--- javax.servlet:javax.servlet-api:4.0.1
#12 62.29 +--- org.springframework.boot:spring-boot-starter-cache -> 2.7.18
#12 62.29 |    +--- org.springframework.boot:spring-boot-starter:2.7.18
#12 62.29 |    |    +--- org.springframework.boot:spring-boot:2.7.18
#12 62.29 |    |    |    +--- org.springframework:spring-core:5.3.31
#12 62.29 |    |    |    |    \--- org.springframework:spring-jcl:5.3.31
#12 62.29 |    |    |    \--- org.springframework:spring-context:5.3.31
#12 62.29 |    |    |         +--- org.springframework:spring-aop:5.3.31
#12 62.29 |    |    |         |    +--- org.springframework:spring-beans:5.3.31
#12 62.29 |    |    |         |    |    \--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 |    |    |         |    \--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 |    |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.29 |    |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 |    |    |         \--- org.springframework:spring-expression:5.3.31
#12 62.29 |    |    |              \--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.7.18
#12 62.29 |    |    |    \--- org.springframework.boot:spring-boot:2.7.18 (*)
#12 62.29 |    |    +--- org.springframework.boot:spring-boot-starter-logging:2.7.18
#12 62.29 |    |    |    +--- ch.qos.logback:logback-classic:1.2.12
#12 62.29 |    |    |    |    +--- ch.qos.logback:logback-core:1.2.12
#12 62.29 |    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 62.29 |    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.17.2
#12 62.29 |    |    |    |    +--- org.slf4j:slf4j-api:1.7.35 -> 1.7.36
#12 62.29 |    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.17.2 -> 2.13.2
#12 62.29 |    |    |    \--- org.slf4j:jul-to-slf4j:1.7.36
#12 62.29 |    |    |         \--- org.slf4j:slf4j-api:1.7.36
#12 62.29 |    |    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
#12 62.29 |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 |    |    \--- org.yaml:snakeyaml:1.30
#12 62.29 |    \--- org.springframework:spring-context-support:5.3.31
#12 62.29 |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.29 |         +--- org.springframework:spring-context:5.3.31 (*)
#12 62.29 |         \--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 +--- org.springframework.boot:spring-boot-starter-data-jpa -> 2.7.18
#12 62.29 |    +--- org.springframework.boot:spring-boot-starter-aop:2.7.18
#12 62.29 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 62.29 |    |    +--- org.springframework:spring-aop:5.3.31 (*)
#12 62.29 |    |    \--- org.aspectj:aspectjweaver:1.9.7
#12 62.29 |    +--- org.springframework.boot:spring-boot-starter-jdbc:2.7.18
#12 62.29 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 62.29 |    |    +--- com.zaxxer:HikariCP:4.0.3
#12 62.29 |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
#12 62.29 |    |    \--- org.springframework:spring-jdbc:5.3.31
#12 62.29 |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.29 |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 |    |         \--- org.springframework:spring-tx:5.3.31
#12 62.29 |    |              +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.29 |    |              \--- org.springframework:spring-core:5.3.31 (*)
#12 62.29 |    +--- jakarta.transaction:jakarta.transaction-api:1.3.3
#12 62.29 |    +--- jakarta.persistence:jakarta.persistence-api:2.2.3
#12 62.29 |    +--- org.hibernate:hibernate-core:5.6.15.Final
#12 62.29 |    |    +--- org.jboss.logging:jboss-logging:3.4.3.Final
#12 62.29 |    |    +--- net.bytebuddy:byte-buddy:1.12.18 -> 1.12.23
#12 62.29 |    |    +--- antlr:antlr:2.7.7
#12 62.29 |    |    +--- org.jboss:jandex:2.4.2.Final
#12 62.30 |    |    +--- com.fasterxml:classmate:1.5.1
#12 62.30 |    |    +--- org.hibernate.common:hibernate-commons-annotations:5.1.2.Final
#12 62.30 |    |    |    \--- org.jboss.logging:jboss-logging:3.3.2.Final -> 3.4.3.Final
#12 62.30 |    |    \--- org.glassfish.jaxb:jaxb-runtime:2.3.1 -> 2.3.9
#12 62.30 |    |         +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.3
#12 62.30 |    |         |    \--- jakarta.activation:jakarta.activation-api:1.2.2
#12 62.30 |    |         +--- org.glassfish.jaxb:txw2:2.3.9
#12 62.30 |    |         \--- com.sun.istack:istack-commons-runtime:3.0.12
#12 62.30 |    +--- org.springframework.data:spring-data-jpa:2.7.18
#12 62.30 |    |    +--- org.springframework.data:spring-data-commons:2.7.18
#12 62.30 |    |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 62.30 |    |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.30 |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 62.30 |    |    +--- org.springframework:spring-orm:5.3.31
#12 62.30 |    |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.30 |    |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 62.30 |    |    |    +--- org.springframework:spring-jdbc:5.3.31 (*)
#12 62.30 |    |    |    \--- org.springframework:spring-tx:5.3.31 (*)
#12 62.30 |    |    +--- org.springframework:spring-context:5.3.31 (*)
#12 62.30 |    |    +--- org.springframework:spring-aop:5.3.31 (*)
#12 62.30 |    |    +--- org.springframework:spring-tx:5.3.31 (*)
#12 62.30 |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.30 |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 62.30 |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 62.30 |    \--- org.springframework:spring-aspects:5.3.31
#12 62.30 |         \--- org.aspectj:aspectjweaver:1.9.7
#12 62.30 +--- org.springframework.boot:spring-boot-starter-thymeleaf -> 2.7.18
#12 62.30 |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 62.30 |    +--- org.thymeleaf:thymeleaf-spring5:3.0.15.RELEASE
#12 62.30 |    |    +--- org.thymeleaf:thymeleaf:3.0.15.RELEASE
#12 62.30 |    |    |    +--- org.attoparser:attoparser:2.0.5.RELEASE
#12 62.30 |    |    |    +--- org.unbescape:unbescape:1.1.6.RELEASE
#12 62.30 |    |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 62.30 |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 62.30 |    \--- org.thymeleaf.extras:thymeleaf-extras-java8time:3.0.4.RELEASE
#12 62.30 |         +--- org.thymeleaf:thymeleaf:3.0.11.RELEASE -> 3.0.15.RELEASE (*)
#12 62.30 |         \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 62.30 +--- org.springframework.boot:spring-boot-starter-web -> 2.7.18
#12 62.30 |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 62.30 |    +--- org.springframework.boot:spring-boot-starter-json:2.7.18
#12 62.30 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 62.30 |    |    +--- org.springframework:spring-web:5.3.31
#12 62.30 |    |    |    +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.30 |    |    |    \--- org.springframework:spring-core:5.3.31 (*)
#12 62.30 |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.5
#12 62.30 |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.5
#12 62.30 |    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5
#12 62.30 |    |    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.13.5 (c)
#12 62.30 |    |    |    |         +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (c)
#12 62.30 |    |    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (c)
#12 62.30 |    |    |    |         +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.5 (c)
#12 62.30 |    |    |    |         +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.5 (c)
#12 62.30 |    |    |    |         \--- com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.5 (c)
#12 62.30 |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.5
#12 62.30 |    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 62.30 |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 62.30 |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.5
#12 62.30 |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (*)
#12 62.30 |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (*)
#12 62.30 |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 62.30 |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.5
#12 62.30 |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.5 (*)
#12 62.30 |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (*)
#12 62.30 |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (*)
#12 62.30 |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 62.30 |    |    \--- com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.5
#12 62.30 |    |         +--- com.fasterxml.jackson.core:jackson-core:2.13.5 (*)
#12 62.30 |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.5 (*)
#12 62.30 |    |         \--- com.fasterxml.jackson:jackson-bom:2.13.5 (*)
#12 62.30 |    +--- org.springframework:spring-web:5.3.31 (*)
#12 62.30 |    \--- org.springframework:spring-webmvc:5.3.31
#12 62.30 |         +--- org.springframework:spring-aop:5.3.31 (*)
#12 62.30 |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 62.30 |         +--- org.springframework:spring-context:5.3.31 (*)
#12 62.30 |         +--- org.springframework:spring-core:5.3.31 (*)
#12 62.30 |         +--- org.springframework:spring-expression:5.3.31 (*)
#12 62.30 |         \--- org.springframework:spring-web:5.3.31 (*)
#12 62.30 +--- org.springframework.boot:spring-boot-starter-validation -> 2.7.18
#12 62.30 |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 62.30 |    +--- org.apache.tomcat.embed:tomcat-embed-el:9.0.83
#12 62.30 |    \--- org.hibernate.validator:hibernate-validator:6.2.5.Final
#12 62.30 |         +--- jakarta.validation:jakarta.validation-api:2.0.2
#12 62.30 |         +--- org.jboss.logging:jboss-logging:3.4.1.Final -> 3.4.3.Final
#12 62.30 |         \--- com.fasterxml:classmate:1.5.1
#12 62.30 +--- javax.cache:cache-api -> 1.1.1
#12 62.30 +--- jakarta.xml.bind:jakarta.xml.bind-api -> 2.3.3 (*)
#12 62.30 +--- junit:junit:4.13
#12 62.30 |    \--- org.hamcrest:hamcrest-core:1.3 -> 2.2
#12 62.30 |         \--- org.hamcrest:hamcrest:2.2
#12 62.30 +--- org.mockito:mockito-core:3.3.3
#12 62.30 |    +--- net.bytebuddy:byte-buddy:1.10.5 -> 1.12.23
#12 62.30 |    +--- net.bytebuddy:byte-buddy-agent:1.10.5 -> 1.12.23
#12 62.30 |    \--- org.objenesis:objenesis:2.6
#12 62.30 +--- me.gosimple:nbvcxz:1.4.3
#12 62.30 +--- nl.jqno.equalsverifier:equalsverifier:3.1.13
#12 62.30 +--- io.cucumber:cucumber-java:5.7.0
#12 62.30 |    +--- io.cucumber:cucumber-core:5.7.0
#12 62.30 |    |    +--- io.cucumber:cucumber-gherkin:5.7.0
#12 62.30 |    |    |    \--- io.cucumber:cucumber-plugin:5.7.0
#12 62.30 |    |    |         \--- org.apiguardian:apiguardian-api:1.1.0
#12 62.30 |    |    +--- io.cucumber:cucumber-gherkin-vintage:5.7.0
#12 62.30 |    |    |    \--- io.cucumber:cucumber-gherkin:5.7.0 (*)
#12 62.30 |    |    +--- io.cucumber:tag-expressions:2.0.4
#12 62.30 |    |    +--- io.cucumber:cucumber-expressions:8.3.1
#12 62.39 |    |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 62.39 |    |    +--- io.cucumber:datatable:3.3.1
#12 62.39 |    |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 62.39 |    |    +--- io.cucumber:cucumber-plugin:5.7.0 (*)
#12 62.39 |    |    +--- io.cucumber:docstring:5.7.0
#12 62.39 |    |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 62.39 |    |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 62.39 |    \--- org.apiguardian:apiguardian-api:1.1.0
#12 62.39 +--- io.cucumber:cucumber-junit:5.7.0
#12 62.39 |    +--- org.apiguardian:apiguardian-api:1.1.0
#12 62.39 |    +--- io.cucumber:cucumber-core:5.7.0 (*)
#12 62.39 |    \--- junit:junit:4.13 (*)
#12 62.39 +--- org.apache.commons:commons-lang3:3.10
#12 62.39 +--- org.apache.logging.log4j:log4j-api:2.13.2
#12 62.39 +--- org.apache.logging.log4j:log4j-core:2.13.2
#12 62.39 |    \--- org.apache.logging.log4j:log4j-api:2.13.2
#12 62.39 +--- org.apache.logging.log4j:log4j-slf4j-impl:2.13.2
#12 62.39 |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.36
#12 62.39 |    \--- org.apache.logging.log4j:log4j-api:2.13.2
#12 62.39 +--- org.flywaydb:flyway-core:6.4.1
#12 62.39 +--- net.bull.javamelody:javamelody-core:1.85.0
#12 62.39 |    \--- org.jrobin:jrobin:1.5.9
#12 62.39 \--- com.h2database:h2:1.4.200
#12 62.39
#12 62.39 compileOnly - Compile only dependencies for source set 'main'. (n)
#12 62.39 \--- org.checkerframework:checker-qual:3.3.0 (n)
#12 62.39
#12 62.39 compileOnlyApi - Compile only API dependencies for source set 'main'. (n)
#12 62.39 No dependencies
#12 62.39
#12 62.39 coverageDataElementsForTest - Binary data file containing results of Jacoco test coverage reporting for the test Test Suite's test target. (n)
#12 62.39 No dependencies
#12 62.39
#12 62.39 cucumberBddTestAnnotationProcessor - Annotation processors and their dependencies for source set 'cucumber bdd test'.
#12 62.39 No dependencies
#12 62.39
#12 62.39 cucumberBddTestCompileClasspath - Compile classpath for source set 'cucumber bdd test'.
#12 65.79 +--- javax.servlet:javax.servlet-api:4.0.1
#12 65.79 +--- org.springframework.boot:spring-boot-starter-cache -> 2.7.18
#12 65.79 |    +--- org.springframework.boot:spring-boot-starter:2.7.18
#12 65.79 |    |    +--- org.springframework.boot:spring-boot:2.7.18
#12 65.79 |    |    |    +--- org.springframework:spring-core:5.3.31
#12 65.79 |    |    |    |    \--- org.springframework:spring-jcl:5.3.31
#12 65.79 |    |    |    \--- org.springframework:spring-context:5.3.31
#12 65.79 |    |    |         +--- org.springframework:spring-aop:5.3.31
#12 65.79 |    |    |         |    +--- org.springframework:spring-beans:5.3.31
#12 65.79 |    |    |         |    |    \--- org.springframework:spring-core:5.3.31 (*)
#12 65.79 |    |    |         |    \--- org.springframework:spring-core:5.3.31 (*)
#12 65.79 |    |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 65.79 |    |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 65.79 |    |    |         \--- org.springframework:spring-expression:5.3.31
#12 65.79 |    |    |              \--- org.springframework:spring-core:5.3.31 (*)
#12 65.79 |    |    +--- org.springframework.boot:spring-boot-autoconfigure:2.7.18
#12 65.79 |    |    |    \--- org.springframework.boot:spring-boot:2.7.18 (*)
#12 65.79 |    |    +--- org.springframework.boot:spring-boot-starter-logging:2.7.18
#12 65.79 |    |    |    +--- ch.qos.logback:logback-classic:1.2.12
#12 65.79 |    |    |    |    +--- ch.qos.logback:logback-core:1.2.12
#12 65.79 |    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
#12 65.79 |    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.17.2
#12 65.79 |    |    |    |    +--- org.slf4j:slf4j-api:1.7.35 -> 1.7.36
#12 65.79 |    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.17.2 -> 2.13.2
#12 65.79 |    |    |    \--- org.slf4j:jul-to-slf4j:1.7.36
#12 65.79 |    |    |         \--- org.slf4j:slf4j-api:1.7.36
#12 65.79 |    |    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
#12 65.79 |    |    +--- org.springframework:spring-core:5.3.31 (*)
#12 65.79 |    |    \--- org.yaml:snakeyaml:1.30
#12 65.79 |    \--- org.springframework:spring-context-support:5.3.31
#12 65.79 |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 65.79 |         +--- org.springframework:spring-context:5.3.31 (*)
#12 65.79 |         \--- org.springframework:spring-core:5.3.31 (*)
#12 65.79 +--- org.springframework.boot:spring-boot-starter-data-jpa -> 2.7.18
#12 65.79 |    +--- org.springframework.boot:spring-boot-starter-aop:2.7.18
#12 65.79 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 65.79 |    |    +--- org.springframework:spring-aop:5.3.31 (*)
#12 65.79 |    |    \--- org.aspectj:aspectjweaver:1.9.7
#12 65.79 |    +--- org.springframework.boot:spring-boot-starter-jdbc:2.7.18
#12 65.79 |    |    +--- org.springframework.boot:spring-boot-starter:2.7.18 (*)
#12 65.79 |    |    +--- com.zaxxer:HikariCP:4.0.3
#12 65.79 |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
#12 65.79 |    |    \--- org.springframework:spring-jdbc:5.3.31
#12 65.79 |    |         +--- org.springframework:spring-beans:5.3.31 (*)
#12 65.79 |    |         +--- org.springframework:spring-core:5.3.31 (*)
#12 65.79 |    |         \--- org.springframework:spring-tx:5.3.31
#12 65.79 |    |              +--- org.springframework:spring-beans:5.3.31 (*)
#12 65.79 |    |              \--- org.springframework:spring-core:5.3.31 (*)

32 tests completed, 5 failed

> Task :jacocoTestReport
Cached resource https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.pom is up-to-date (lastModified: Sat Feb 06 12:31:13 UTC 2021).
Cached resource https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.pom is up-to-date (lastModified: Sat Feb 06 12:31:19 UTC 2021).
Excluding []
Caching disabled for task ':jacocoTestReport' because:
  Build cache is disabled
Task ':jacocoTestReport' is not up-to-date because:
  No history is available.
[ant:jacocoReport] Loading execution data file /app/build/jacoco/test.exec
[ant:jacocoReport] Writing bundle 'app' with 14 classes
:jacocoTestReport (Thread[included builds,5,main]) completed. Took 0.893 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 3 executed, 2 up-to-date
Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
Created user preferences directory.
Stopped 1 worker daemon(s).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///app/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

ERROR:refacteval:Test run failed for 'persistence-tests' with exit code 1.
INFO:refacteval:Entering cleanup and report extraction phase...
INFO:refacteval:Gradle test reports copied to /var/folders/rx/vycj7vys6v78_nd6qmwm7nj40000gn/T/tmpo20t6dq0
INFO:refacteval:Output directory /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/3 exists but is empty. Proceeding to copy reports.
INFO:refacteval:Test reports copied to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/3
INFO:refacteval:Tearing down Docker Compose environment...
INFO:refacteval:...and removing images.
INFO:refacteval:Environment torn down successfully.
INFO:refacteval:--- Test run for microservice: 3 finished ---
INFO:refacteval:--- Starting test run for microservice: 2 ---
INFO:refacteval:Working directory: /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microrefact/7ep-demo
INFO:refacteval:Reports will be saved to: /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/2
INFO:refacteval:No server services to start.
INFO:refacteval:Running test container for service: 'mathematics-tests'
time="2025-12-08T16:57:08-05:00" level=warning msg="/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/microrefact/7ep-demo/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 Network 7ep-demo_testing_network  Creating
 Network 7ep-demo_testing_network  Created
time="2025-12-08T16:57:08-05:00" level=warning msg="Found orphan containers ([persistence-tests-cont-1765230910 library-tests-cont-1765230779 authentication-tests-cont-1765230554]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."

Testing 3 failed with error: Command '['docker-compose', 'run', '--name', 'persistence-tests-cont-1765230910', 'persistence-tests']' returned non-zero exit status 1.
Testing 2...
Creating report directory for 2 at /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/2
#1 [internal] load local bake definitions
#1 reading from stdin 725B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.15kB done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/gradle:7.4.2-jdk11-jammy
#3 DONE 0.0s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [build 1/9] FROM docker.io/library/gradle:7.4.2-jdk11-jammy
#5 DONE 0.0s

#6 [internal] load build context
#6 transferring context: 209.79kB 0.0s done
#6 DONE 0.0s

#7 [build 5/9] COPY gradle* ./
#7 CACHED

#8 [build 4/9] COPY gradle ./gradle
#8 CACHED

#9 [build 2/9] WORKDIR /app
#9 CACHED

#10 [build 6/9] COPY src/main/webapp ./src/main/webapp
#10 CACHED

#11 [build 3/9] COPY build.gradle settings.gradle* ./
#11 CACHED

#12 [build 7/9] RUN gradle dependencies --no-daemon
#12 CACHED

#13 [build 8/9] COPY src ./src
#13 DONE 0.2s

#14 [build 9/9] RUN gradle clean assemble
#14 0.413 Starting a Gradle Daemon (subsequent builds will be faster)
#14 4.409 > Task :clean
#14 12.71 > Task :compileJava
#14 12.71 > Task :writeGitCommitToFile UP-TO-DATE
#14 12.71 > Task :processResources
#14 12.71 > Task :classes
#14 13.91 > Task :bootWarMainClassName
#14 14.21 > Task :bootWar
#14 15.60 > Task :war
#14 15.60 > Task :assemble
#14 15.60
#14 15.60 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
#14 15.60
#14 15.60 You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
#14 15.60
#14 15.60 See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
#14 15.60
#14 15.60 BUILD SUCCESSFUL in 15s
#14 15.60 6 actionable tasks: 6 executed
#14 DONE 16.2s

#15 [test 1/1] RUN echo '#!/bin/bash\nif [ "$1" = "" ]; then\n  gradle test --info --no-daemon\nelse\n  gradle test --info --tests "$@" --no-daemon\nfi' > /app/run-tests.sh && chmod +x /app/run-tests.sh
#15 DONE 0.1s

#16 exporting to image
#16 exporting layers
#16 exporting layers 0.2s done
#16 writing image sha256:da848fcc4742fa12ffccf3b20fa05cb9fae3d4804cdeb3b206b83ac162892756 done
#16 naming to docker.io/library/7ep-demo-mathematics-tests done
#16 DONE 0.2s

#17 resolving provenance for metadata file
#17 DONE 0.0s
Initialized native services in: /home/gradle/.gradle/native
Initialized jansi services in: /home/gradle/.gradle/native
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Starting process 'Gradle build daemon'. Working directory: /home/gradle/.gradle/daemon/7.4.2 Command: /opt/java/openjdk/bin/java -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx1g -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /opt/gradle/lib/gradle-launcher-7.4.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.2
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 0.437 secs.
The client will now receive all logging from the daemon (pid: 42). The daemon log file: /home/gradle/.gradle/daemon/7.4.2/daemon-42.out.log
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Daemon will be stopped at the end of the build
Using 1 worker leases.
Watching the file system is configured to be enabled if available
Not watching /app since the file system is not supported
File system watching is active
Starting Build
Settings evaluated using settings file '/app/settings.gradle'.
Projects loaded. Root project using build file '/app/build.gradle'.
Included projects: [root project 'app']

> Configure project :
Evaluating root project 'app' using build file '/app/build.gradle'.
Applying dependency management to configuration 'annotationProcessor' in project 'app'
Applying dependency management to configuration 'apiElements' in project 'app'
Applying dependency management to configuration 'archives' in project 'app'
Applying dependency management to configuration 'bootArchives' in project 'app'
Applying dependency management to configuration 'compileClasspath' in project 'app'
Applying dependency management to configuration 'compileOnly' in project 'app'
Applying dependency management to configuration 'coverageDataElementsForTest' in project 'app'
Applying dependency management to configuration 'default' in project 'app'
Applying dependency management to configuration 'developmentOnly' in project 'app'
Applying dependency management to configuration 'gretty' in project 'app'
Applying dependency management to configuration 'grettyNoSpringBoot' in project 'app'
Applying dependency management to configuration 'grettyProductRuntime' in project 'app'
Applying dependency management to configuration 'grettyProvidedCompile' in project 'app'
Applying dependency management to configuration 'grettyRunnerJetty7' in project 'app'
Applying dependency management to configuration 'grettyRunnerJetty8' in project 'app'
Applying dependency management to configuration 'grettyRunnerJetty9' in project 'app'
Applying dependency management to configuration 'grettyRunnerJetty93' in project 'app'
Applying dependency management to configuration 'grettyRunnerJetty94' in project 'app'
Applying dependency management to configuration 'grettyRunnerTomcat85' in project 'app'
Applying dependency management to configuration 'grettyRunnerTomcat9' in project 'app'
Applying dependency management to configuration 'grettySpringLoaded' in project 'app'
Applying dependency management to configuration 'grettyStarter' in project 'app'
Applying dependency management to configuration 'implementation' in project 'app'
Applying dependency management to configuration 'jacocoAgent' in project 'app'
Applying dependency management to configuration 'jacocoAnt' in project 'app'
Applying dependency management to configuration 'mainSourceElements' in project 'app'
Applying dependency management to configuration 'pitest' in project 'app'
Applying dependency management to configuration 'productionRuntimeClasspath' in project 'app'
Applying dependency management to configuration 'providedCompile' in project 'app'
Applying dependency management to configuration 'providedRuntime' in project 'app'
Applying dependency management to configuration 'runtimeClasspath' in project 'app'
Applying dependency management to configuration 'runtimeElements' in project 'app'
Applying dependency management to configuration 'runtimeOnly' in project 'app'
Applying dependency management to configuration 'springBoot' in project 'app'
Applying dependency management to configuration 'testAnnotationProcessor' in project 'app'
Applying dependency management to configuration 'testCompileClasspath' in project 'app'
Applying dependency management to configuration 'testCompileOnly' in project 'app'
Applying dependency management to configuration 'testImplementation' in project 'app'
Applying dependency management to configuration 'testResultsElementsForTest' in project 'app'
Applying dependency management to configuration 'testRuntimeClasspath' in project 'app'
Applying dependency management to configuration 'testRuntimeOnly' in project 'app'
Found plugin java, applying checker compiler options.
Applying dependency management to configuration 'checkerFrameworkAnnotatedJDK' in project 'app'
Applying dependency management to configuration 'checkerFramework' in project 'app'
Applying dependency management to configuration 'errorProneJavac' in project 'app'
Applying dependency management to configuration 'api' in project 'app'
Applying dependency management to configuration 'compileOnlyApi' in project 'app'
Applying dependency management to configuration 'integrationTestsImplementation' in project 'app'
Applying dependency management to configuration 'integrationTestsCompileOnly' in project 'app'
Applying dependency management to configuration 'integrationTestsCompileClasspath' in project 'app'
Applying dependency management to configuration 'integrationTestsAnnotationProcessor' in project 'app'
Applying dependency management to configuration 'integrationTestsRuntimeOnly' in project 'app'
Applying dependency management to configuration 'integrationTestsRuntimeClasspath' in project 'app'
Applying dependency management to configuration 'cucumberBddTestImplementation' in project 'app'
Applying dependency management to configuration 'cucumberBddTestCompileOnly' in project 'app'
Applying dependency management to configuration 'cucumberBddTestCompileClasspath' in project 'app'
Applying dependency management to configuration 'cucumberBddTestAnnotationProcessor' in project 'app'
Applying dependency management to configuration 'cucumberBddTestRuntimeOnly' in project 'app'
Applying dependency management to configuration 'cucumberBddTestRuntimeClasspath' in project 'app'
Resolving global dependency management for project 'app'
Excluding []
Applying dependency management to configuration 'localDeps' in project 'app'
Using PIT: 1.5.1
All projects evaluated.
Selected primary task 'test' from project :
Tasks to be executed: [task ':compileJava', task ':writeGitCommitToFile', task ':processResources', task ':classes', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test', task ':jacocoTestReport']
Tasks that were excluded: []
:compileJava (Thread[included builds,5,main]) started.

> Task :compileJava UP-TO-DATE
Excluding [ognl:ognl, org.javassist:javassist]
Excluding []
Excluding []
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Skipping task ':compileJava' as it is up-to-date.
:compileJava (Thread[included builds,5,main]) completed. Took 0.476 secs.
:writeGitCommitToFile (Thread[included builds,5,main]) started.

> Task :writeGitCommitToFile UP-TO-DATE
Skipping task ':writeGitCommitToFile' as it has no actions.
:writeGitCommitToFile (Thread[included builds,5,main]) completed. Took 0.0 secs.
:processResources (Thread[included builds,5,main]) started.

> Task :processResources UP-TO-DATE
Caching disabled for task ':processResources' because:
  Build cache is disabled
Skipping task ':processResources' as it is up-to-date.
:processResources (Thread[included builds,5,main]) completed. Took 0.004 secs.
:classes (Thread[included builds,5,main]) started.

> Task :classes UP-TO-DATE
Skipping task ':classes' as it has no actions.
:classes (Thread[included builds,5,main]) completed. Took 0.0 secs.
:compileTestJava (Thread[included builds,5,main]) started.
This JVM does not support getting OS memory, so no OS memory status updates will be broadcast

> Task :compileTestJava
Excluding []
Excluding []
Caching disabled for task ':compileTestJava' because:
  Build cache is disabled
Task ':compileTestJava' is not up-to-date because:
  No history is available.
The input changes require a full rebuild for incremental task ':compileTestJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with toolchain '/opt/java/openjdk'.
Starting process 'Gradle Worker Daemon 1'. Working directory: /home/gradle/.gradle/workers Command: /opt/java/openjdk/bin/java --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED @/home/gradle/.gradle/.tmp/gradle-worker-classpath13745291934922392109txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 1'
Successfully started process 'Gradle Worker Daemon 1'
Started Gradle worker daemon (0.183 secs) with fork options DaemonForkOptions{executable=/opt/java/openjdk/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED], keepAliveMode=SESSION}.
Compiling with JDK Java compiler API.
Class dependency analysis for incremental compilation took 0.022 secs.
Created classpath snapshot for incremental compilation in 1.138 secs.
:compileTestJava (Thread[included builds,5,main]) completed. Took 2.482 secs.
:processTestResources (Thread[included builds,5,main]) started.

> Task :processTestResources NO-SOURCE
Skipping task ':processTestResources' as it has no source files and no previous output files.
:processTestResources (Thread[included builds,5,main]) completed. Took 0.002 secs.
:testClasses (Thread[included builds,5,main]) started.

> Task :testClasses
Skipping task ':testClasses' as it has no actions.
:testClasses (Thread[included builds,5,main]) completed. Took 0.0 secs.
:test (Thread[included builds,5,main]) started.
Gradle Test Executor 2 started executing tests.
Gradle Test Executor 2 finished executing tests.

> Task :test FAILED
Excluding []
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  No history is available.
:test.maxParallelForks (5) is larger than max-workers (1), forcing it to 1
Starting process 'Gradle Test Executor 2'. Working directory: /app Command: /opt/java/openjdk/bin/java -Dorg.gradle.internal.worker.tmpdir=/app/build/tmp/test/work -Dorg.gradle.native=false -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.7.jar_3a83c50b4a016f281c4e9f3500d16b55/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false @/home/gradle/.gradle/.tmp/gradle-worker-classpath5834417434385752133txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 2'
Successfully started process 'Gradle Test Executor 2'

com.coveros.training.mathematics.AckServletTests > testPostService_HappyPath FAILED
    java.lang.NullPointerException
        at com.coveros.training.mathematics.AckServlet.doPost(AckServlet.java:73)
        at com.coveros.training.mathematics.AckServletTests.testPostService_HappyPath(AckServletTests.java:33)

com.coveros.training.mathematics.CalculatorTests > testShouldMockOutsideMethodsPart2 SKIPPED

com.coveros.training.mathematics.CalculatorTests > testShouldGetPairResult SKIPPED

com.coveros.training.mathematics.CalculatorTests > testShouldAddTwoDecimals SKIPPED

com.coveros.training.mathematics.CalculatorTests > testShouldAddTwoIntegers SKIPPED

com.coveros.training.mathematics.CalculatorTests > testShouldMockOutsideMethods SKIPPED

com.coveros.training.mathematics.CalculatorTests > testShouldGetStringVersionOfResult SKIPPED

com.coveros.training.mathematics.FibServletTests > testPostService_tailRecursive1 FAILED
    java.lang.NullPointerException
        at com.coveros.training.mathematics.FibServlet.doPost(FibServlet.java:84)
        at com.coveros.training.mathematics.FibServletTests.testPostService_tailRecursive1(FibServletTests.java:46)

com.coveros.training.mathematics.FibServletTests > testPostService_tailRecursive2 FAILED
    java.lang.NullPointerException
        at com.coveros.training.mathematics.FibServlet.doPost(FibServlet.java:84)
        at com.coveros.training.mathematics.FibServletTests.testPostService_tailRecursive2(FibServletTests.java:60)

com.coveros.training.mathematics.FibServletTests > testPostService_HappyPath FAILED
    java.lang.NullPointerException
        at com.coveros.training.mathematics.FibServlet.doPost(FibServlet.java:84)
        at com.coveros.training.mathematics.FibServletTests.testPostService_HappyPath(FibServletTests.java:32)

com.coveros.training.mathematics.MathServletTests > testPostService_HappyPath FAILED
    java.lang.NullPointerException
        at com.coveros.training.mathematics.MathServlet.doPost(MathServlet.java:55)
        at com.coveros.training.mathematics.MathServletTests.testPostService_HappyPath(MathServletTests.java:32)
Finished generating test XML results (0.009 secs) into: /app/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.013 secs) into: /app/build/reports/tests/test
:test (Thread[included builds,5,main]) completed. Took 1.598 secs.
:jacocoTestReport (Thread[included builds,5,main]) started.

73 tests completed, 5 failed, 6 skipped

> Task :jacocoTestReport
Cached resource https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.pom is up-to-date (lastModified: Sat Feb 06 12:31:13 UTC 2021).
Cached resource https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.pom is up-to-date (lastModified: Sat Feb 06 12:31:19 UTC 2021).
Excluding []
Caching disabled for task ':jacocoTestReport' because:
  Build cache is disabled
Task ':jacocoTestReport' is not up-to-date because:
  No history is available.
[ant:jacocoReport] Loading execution data file /app/build/jacoco/test.exec
[ant:jacocoReport] Writing bundle 'app' with 28 classes
:jacocoTestReport (Thread[included builds,5,main]) completed. Took 0.857 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 3 executed, 2 up-to-date
Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
Created user preferences directory.
Stopped 1 worker daemon(s).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///app/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

ERROR:refacteval:Test run failed for 'mathematics-tests' with exit code 1.
INFO:refacteval:Entering cleanup and report extraction phase...
INFO:refacteval:Gradle test reports copied to /var/folders/rx/vycj7vys6v78_nd6qmwm7nj40000gn/T/tmpeatzb78c
INFO:refacteval:Output directory /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/2 exists but is empty. Proceeding to copy reports.
INFO:refacteval:Test reports copied to /Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/microrefact/7ep-demo/2
INFO:refacteval:Tearing down Docker Compose environment...
INFO:refacteval:...and removing images.
INFO:refacteval:Environment torn down successfully.
INFO:refacteval:--- Test run for microservice: 2 finished ---

Testing 2 failed with error: Command '['docker-compose', 'run', '--name', 'mathematics-tests-cont-1765231028', 'mathematics-tests']' returned non-zero exit status 1.

In [33]:
5

5

## Parse the reports

### Monoliths

In [46]:
app = "spring-petclinic" #"jpetstore-6"  #"7ep-demo"
reports_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports"
app_report_path = Path(f"{reports_path}/monoliths/{app}")

In [35]:
from refacteval.testing.report import ReportParser

In [48]:
parser = ReportParser()

report = parser.extract(app_report_path)

Skipping testTriggerException

In [53]:
report['org.springframework.samples.petclinic.owner.OwnerControllerTests']['test_cases'].keys()

dict_keys(['testProcessUpdateOwnerFormHasErrors', 'testProcessCreationFormSuccess', 'testInitFindForm', 'testShowOwner', 'testInitUpdateOwnerForm', 'testInitCreationForm', 'testProcessFindFormByLastName', 'testProcessFindFormNoOwnersFound', 'testProcessFindFormSuccess', 'testProcessUpdateOwnerFormSuccess', 'testProcessCreationFormHasErrors', 'testProcessUpdateOwnerFormUnchangedSuccess'])

In [34]:
import pandas as pd

INFO:numexpr.utils:NumExpr defaulting to 10 threads.

In [73]:
columns = ["app", "ms_name_or_monolith", "test_class", "test_method", "status", "time"]
reports_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports"

rows = []
rows_per_app = {}

for app in ["spring-petclinic", "jpetstore-6", "7ep-demo"]:
    app_report_path = Path(f"{reports_path}/monoliths/{app}")
    print(f"Testing {app}...")
    rows_per_app[app] = []
    parser = ReportParser()
    report = parser.extract(app_report_path)
    print(f"Report for {app}:")
    for test_class in report:
        print(f"Test class: {test_class}")
        for test_method in report[test_class]['test_cases']:
            print(f"  Test method: {test_method}")
            print(f"    Status: {report[test_class]['test_cases'][test_method]['status']}")
            print(f"    Time: {report[test_class]['test_cases'][test_method]['time']}")
            rows.append({
                "app": app,
                "ms_name_or_monolith": "monolith",
                "test_class": test_class,
                "test_method": test_method,
                "status": report[test_class]['test_cases'][test_method]['status'],
                "time": report[test_class]['test_cases'][test_method]['time'],
            })
            rows_per_app[app].append(report[test_class]['test_cases'][test_method]['status'])
        print()
    print("="*100)
    print()

df_mono = pd.DataFrame(rows, columns=columns)

Skipping testTriggerException
Skipping testShouldPerformWell
Skipping testShouldBe16Years3Months_HappyPath
Skipping testShouldReturnEvenTime
Skipping testShouldMockOutsideMethodsPart2
Skipping testShouldGetPairResult
Skipping testShouldAddTwoDecimals
Skipping testShouldAddTwoIntegers
Skipping testShouldMockOutsideMethods
Skipping testShouldGetStringVersionOfResult
Skipping testShouldHaveSufficientEntropyInPassword
Skipping testShouldHaveInsufficientEntropyInPassword
Skipping testShouldHaveSuccessfulEntropyInPassword

Testing spring-petclinic...
Report for spring-petclinic:
Test class: org.springframework.samples.petclinic.owner.OwnerControllerTests
  Test method: testProcessUpdateOwnerFormHasErrors
    Status: passed
    Time: 0.35
  Test method: testProcessCreationFormSuccess
    Status: passed
    Time: 0.006
  Test method: testInitFindForm
    Status: passed
    Time: 0.01
  Test method: testShowOwner
    Status: passed
    Time: 0.031
  Test method: testInitUpdateOwnerForm
    Status: passed
    Time: 0.012
  Test method: testInitCreationForm
    Status: passed
    Time: 0.01
  Test method: testProcessFindFormByLastName
    Status: passed
    Time: 0.005
  Test method: testProcessFindFormNoOwnersFound
    Status: passed
    Time: 0.007
  Test method: testProcessFindFormSuccess
    Status: passed
    Time: 0.014
  Test method: testProcessUpdateOwnerFormSuccess
    Status: passed
    Time: 0.004
  Test method: testProcessCreationFormHasErrors
    Status: passed
    Time: 0.008
  Test method: testProcessUpdateOwnerFormUnchangedSuccess
    Status: passed
    Time: 0.004

Test class: org.springframework.samples.petclinic.owner.PetControllerTests
  Test method: testProcessCreationFormSuccess
    Status: passed
    Time: 0.008
  Test method: testProcessUpdateFormSuccess
    Status: passed
    Time: 0.004
  Test method: testInitUpdateForm
    Status: passed
    Time: 0.028
  Test method: testInitCreationForm
    Status: passed
    Time: 0.007
  Test method: testProcessCreationFormHasErrors
    Status: passed
    Time: 0.008
  Test method: testProcessUpdateFormHasErrors
    Status: passed
    Time: 0.01

Test class: org.springframework.samples.petclinic.vet.VetControllerTests
  Test method: testShowVetListHtml
    Status: passed
    Time: 0.015
  Test method: testShowResourcesVetList
    Status: passed
    Time: 0.056

Test class: org.springframework.samples.petclinic.vet.VetTests
  Test method: testSerialization
    Status: passed
    Time: 0.005

Test class: org.springframework.samples.petclinic.model.ValidatorTests
  Test method: shouldNotValidateWhenFirstNameEmpty
    Status: passed
    Time: 0.003

Test class: org.springframework.samples.petclinic.owner.VisitControllerTests
  Test method: testProcessNewVisitFormHasErrors
    Status: passed
    Time: 0.021
  Test method: testProcessNewVisitFormSuccess
    Status: passed
    Time: 0.002
  Test method: testInitNewVisitForm
    Status: passed
    Time: 0.004

Test class: org.springframework.samples.petclinic.service.ClinicServiceTests
  Test method: shouldFindVets
    Status: passed
    Time: 0.217
  Test method: shouldFindOwnersByLastName
    Status: passed
    Time: 0.04
  Test method: shouldAddNewVisitForPet
    Status: passed
    Time: 0.036
  Test method: shouldUpdateOwner
    Status: passed
    Time: 0.013
  Test method: shouldFindVisitsByPetId
    Status: passed
    Time: 0.007
  Test method: shouldInsertPetIntoDatabaseAndGenerateId
    Status: passed
    Time: 0.016
  Test method: shouldInsertOwner
    Status: passed
    Time: 0.005
  Test method: shouldFindSingleOwnerWithPet
    Status: passed
    Time: 0.005
  Test method: shouldUpdatePetName
    Status: passed
    Time: 0.008
  Test method: shouldFindAllPetTypes
    Status: passed
    Time: 0.003

Test class: org.springframework.samples.petclinic.system.CrashControllerTests
  Test method: testTriggerException
    Status: skipped
    Time: 0.0

Test class: org.springframework.samples.petclinic.owner.PetTypeFormatterTests
  Test method: shouldThrowParseException
    Status: passed
    Time: 0.012
  Test method: testPrint
    Status: passed
    Time: 0.001
  Test method: shouldParse
    Status: passed
    Time: 0.0

Test class: org.springframework.samples.petclinic.PetClinicIntegrationTests
  Test method: testFindAll
    Status: passed
    Time: 0.016
  Test method: testOwnerDetails
    Status: passed
    Time: 0.14

====================================================================================================

Testing jpetstore-6...
Report for jpetstore-6:
Test class: org.mybatis.jpetstore.mapper.AccountMapperTest
  Test method: updateProfile
    Status: passed
    Time: 0.025
  Test method: getAccountByUsername
    Status: passed
    Time: 0.006
  Test method: insertAccount
    Status: passed
    Time: 0.003
  Test method: updateSignon
    Status: passed
    Time: 0.002
  Test method: insertProfile
    Status: passed
    Time: 0.004
  Test method: getAccountByUsernameAndPassword
    Status: passed
    Time: 0.004
  Test method: insertSignon
    Status: passed
    Time: 0.002
  Test method: updateAccount
    Status: passed
    Time: 0.002

Test class: org.mybatis.jpetstore.web.actions.CatalogActionBeanTest
  Test method: getCategoryOutputNull
    Status: passed
    Time: 0.001
  Test method: constructorOutputNotNull
    Status: passed
    Time: 0.001
  Test method: getCategoryIdOutputNull
    Status: passed
    Time: 0.0
  Test method: getKeywordOutputNull
    Status: passed
    Time: 0.0
  Test method: getProductOutputNull
    Status: passed
    Time: 0.0
  Test method: getProductIdOutputNull
    Status: passed
    Time: 0.0
  Test method: getItemIdOutputNull
    Status: passed
    Time: 0.0
  Test method: getItemOutputNull
    Status: passed
    Time: 0.0
  Test method: getCategoryListOutputNull
    Status: passed
    Time: 0.0
  Test method: getProductListOutputNull
    Status: passed
    Time: 0.0
  Test method: getItemListOutputNull
    Status: passed
    Time: 0.0

Test class: org.mybatis.jpetstore.mapper.OrderMapperTest
  Test method: insertOrderStatus
    Status: passed
    Time: 0.004
  Test method: insertOrder
    Status: passed
    Time: 0.003
  Test method: getOrdersByUsername
    Status: passed
    Time: 0.006
  Test method: getOrder
    Status: passed
    Time: 0.003

Test class: org.mybatis.jpetstore.mapper.CategoryMapperTest
  Test method: getCategoryList
    Status: passed
    Time: 0.002
  Test method: getCategory
    Status: passed
    Time: 0.002

Test class: org.mybatis.jpetstore.service.CatalogServiceTest
  Test method: shouldReturnItemList
    Status: passed
    Time: 0.046
  Test method: shouldReturnCategoryList
    Status: passed
    Time: 0.001
  Test method: shouldCallTheSearchMapperTwice
    Status: passed
    Time: 0.002
  Test method: shouldReturnItem
    Status: passed
    Time: 0.002
  Test method: shouldReturnProduct
    Status: passed
    Time: 0.002
  Test method: shouldReturnProductList
    Status: passed
    Time: 0.003
  Test method: shouldReturnFalseWhenNotExistStock
    Status: passed
    Time: 0.002
  Test method: shouldReturnCategory
    Status: passed
    Time: 0.002
  Test method: shouldReturnTrueWhenExistStock
    Status: passed
    Time: 0.002

Test class: org.mybatis.jpetstore.mapper.LineItemMapperTest
  Test method: getLineItemsByOrderId
    Status: passed
    Time: 0.01
  Test method: insertLineItem
    Status: passed
    Time: 0.01

Test class: org.mybatis.jpetstore.service.AccountServiceTest
  Test method: shouldCallTheMapperToUpdateAnAccount
    Status: passed
    Time: 0.679
  Test method: shouldCallTheMapperToGetAccountAnUsername
    Status: passed
    Time: 0.006
  Test method: shouldCallTheMapperToGetAccountAnUsernameAndPassword
    Status: passed
    Time: 0.001
  Test method: shouldCallTheMapperToInsertAnAccount
    Status: passed
    Time: 0.002

Test class: org.mybatis.jpetstore.web.actions.OrderActionBeanTest
  Test method: getOrderListOutputNull
    Status: passed
    Time: 0.001
  Test method: constructorOutputNotNull
    Status: passed
    Time: 0.0
  Test method: isShippingAddressRequiredOutputFalse
    Status: passed
    Time: 0.0
  Test method: isConfirmedOutputFalse
    Status: passed
    Time: 0.0

Test class: org.mybatis.jpetstore.domain.CartTest
  Test method: addItemWhenIsInStockIsFalse
    Status: passed
    Time: 0.0
  Test method: removeItemByIdWhenItemFound
    Status: passed
    Time: 0.0
  Test method: setQuantityByItemId
    Status: passed
    Time: 0.0
  Test method: removeItemByIdWhenItemNotFound
    Status: passed
    Time: 0.001
  Test method: getSubTotalWhenItemIsEmpty
    Status: passed
    Time: 0.0
  Test method: getSubTotalWhenItemIsExist
    Status: passed
    Time: 0.0
  Test method: incrementQuantityByItemId
    Status: passed
    Time: 0.0
  Test method: addItemWhenIsInStockIsTrue
    Status: passed
    Time: 0.001

Test class: org.mybatis.jpetstore.mapper.ItemMapperTest
  Test method: updateInventoryQuantity
    Status: passed
    Time: 0.003
  Test method: getInventoryQuantity
    Status: passed
    Time: 0.003
  Test method: getItem
    Status: passed
    Time: 0.004
  Test method: getItemListByProduct
    Status: passed
    Time: 0.003

Test class: org.mybatis.jpetstore.mapper.SequenceMapperTest
  Test method: updateSequence
    Status: passed
    Time: 0.104
  Test method: getSequence
    Status: passed
    Time: 0.011

Test class: org.mybatis.jpetstore.service.OrderServiceTest
  Test method: shouldReturnNextId
    Status: passed
    Time: 0.049
  Test method: shouldThrowExceptionWhenSequenceNotFound
    Status: passed
    Time: 0.001
  Test method: shouldReturnOrderWhenGivenOrderIdExistedLineItems
    Status: passed
    Time: 0.001
  Test method: shouldCallTheMapperToInsert
    Status: passed
    Time: 0.003
  Test method: shouldReturnOrderList
    Status: passed
    Time: 0.001
  Test method: shouldReturnOrderWhenGivenOrderIdWithOutLineItems
    Status: passed
    Time: 0.001

Test class: org.mybatis.jpetstore.web.actions.AccountActionBeanTest
  Test method: constructorOutputNotNull
    Status: passed
    Time: 0.001
  Test method: getUsernameOutputNull
    Status: passed
    Time: 0.001
  Test method: isAuthenticatedOutputFalse
    Status: passed
    Time: 0.0
  Test method: getMyListOutputNull
    Status: passed
    Time: 0.0
  Test method: getAccountOutputNotNull
    Status: passed
    Time: 0.0
  Test method: getPasswordOutputNull
    Status: passed
    Time: 0.0

Test class: org.mybatis.jpetstore.domain.OrderTest
  Test method: initOrder
    Status: passed
    Time: 0.001

Test class: org.mybatis.jpetstore.mapper.ProductMapperTest
  Test method: getProduct
    Status: passed
    Time: 0.002
  Test method: searchProductList
    Status: passed
    Time: 0.006
  Test method: getProductListByCategory
    Status: passed
    Time: 0.003

====================================================================================================

Testing 7ep-demo...
Report for 7ep-demo:
Test class: com.coveros.training.authentication.RegisterServletTests
  Test method: testEmptyString_Username
    Status: passed
    Time: 0.045
  Test method: doPostWithoutName
    Status: passed
    Time: 0.002
  Test method: testEmptyString_Password
    Status: passed
    Time: 0.001
  Test method: doPostWithName
    Status: passed
    Time: 0.005

Test class: com.coveros.training.library.LibraryLendServletTests
  Test method: testEmptyString_Book
    Status: passed
    Time: 0.021
  Test method: testHappyPathPost
    Status: passed
    Time: 0.002
  Test method: testDateFunction
    Status: passed
    Time: 0.002
  Test method: testEmptyString_Borrower
    Status: passed
    Time: 0.0

Test class: com.coveros.training.authentication.RegistrationUtilsTests
  Test method: testShouldProcessRegistration_HappyPath
    Status: passed
    Time: 0.127
  Test method: testShouldProcessRegistration_BadPassword
    Status: passed
    Time: 0.143
  Test method: testShouldHaveSufficientEntropyInPassword
    Status: passed
    Time: 0.071
  Test method: testShouldProcessRegistration_ExistingUser
    Status: passed
    Time: 0.0
  Test method: testShouldFailOnShortPassword
    Status: passed
    Time: 0.001
  Test method: testEmptyObject
    Status: passed
    Time: 0.0
  Test method: testShouldFailOnEmptyPassword_EmptyString
    Status: passed
    Time: 0.0
  Test method: testShouldProcessRegistration_EmptyUsername
    Status: passed
    Time: 0.032
  Test method: testShouldPerformWell
    Status: skipped
    Time: 0.0
  Test method: testShouldDetermineIfUserInDatabase
    Status: passed
    Time: 0.001

Test class: com.coveros.training.library.LibraryUtilsTests
  Test method: testCanRegisterBorrower
    Status: passed
    Time: 0.001
  Test method: testCanDeleteBorrower
    Status: passed
    Time: 0.001
  Test method: testShouldThrowExceptionWhenSearchingWithEmptyStringAsBookTitle
    Status: passed
    Time: 0.001
  Test method: testCanSearchForBooksById
    Status: passed
    Time: 0.001
  Test method: testCanSearchForLoanByBorrower
    Status: passed
    Time: 0.001
  Test method: testCanCreateEmpty
    Status: passed
    Time: 0.0
  Test method: testCannotDeleteNonRegisteredBorrower
    Status: passed
    Time: 0.001
  Test method: testCannotRegisterBookWithEmptyString
    Status: passed
    Time: 0.001
  Test method: testCanSearchForBorrowerByName
    Status: passed
    Time: 0.0
  Test method: testCanLendBook
    Status: passed
    Time: 0.0
  Test method: testShouldListAvailableBooks
    Status: passed
    Time: 0.0
  Test method: testCanSearchForLoanByBook
    Status: passed
    Time: 0.0
  Test method: testShouldThrowExceptionWhenSearchingWithLessThanOneAsBookId
    Status: passed
    Time: 0.001
  Test method: testCanSearchForBooksByTitle
    Status: passed
    Time: 0.0
  Test method: testShouldBeAbleToListAllBorrowers
    Status: passed
    Time: 0.001
  Test method: testShouldBeAbleToListAllBooks
    Status: passed
    Time: 0.001
  Test method: testCanRegisterBook
    Status: passed
    Time: 0.0
  Test method: testCanLendBook_wrapperMethod
    Status: passed
    Time: 0.001
  Test method: testCannotDeleteNonRegisteredBook
    Status: passed
    Time: 0.001
  Test method: testCanDeleteBook
    Status: passed
    Time: 0.001

Test class: com.coveros.training.mathematics.MathServletTests
  Test method: testPostService_HappyPath
    Status: passed
    Time: 0.016
  Test method: testPostService_realForward_withException
    Status: passed
    Time: 0.0
  Test method: testPostService_Forward
    Status: passed
    Time: 0.001

Test class: com.coveros.training.library.domainobjects.BookTests
  Test method: testShouldHaveEqualsAndHashcodeImplementedCorrectly
    Status: passed
    Time: 0.006
  Test method: testCanCreateEmpty
    Status: passed
    Time: 0.0
  Test method: testShouldOutputGoodString
    Status: passed
    Time: 0.0

Test class: com.coveros.training.mathematics.AckServletTests
  Test method: testPostService_HappyPath
    Status: passed
    Time: 0.04
  Test method: testPostService_realForward_withException
    Status: passed
    Time: 0.001
  Test method: testPostService_Forward
    Status: passed
    Time: 0.0
  Test method: testPostService_TailRecursive
    Status: passed
    Time: 0.007

Test class: com.coveros.training.authentication.LoginUtilsTests
  Test method: testCanCreateEmpty
    Status: passed
    Time: 0.015
  Test method: testCanSeeIfUserRegistered
    Status: passed
    Time: 0.002

Test class: com.coveros.training.authentication.domainobjects.UserTests
  Test method: testShouldHaveEqualsAndHashcodeImplementedCorrectly
    Status: passed
    Time: 0.006
  Test method: testCanCreateEmpty
    Status: passed
    Time: 0.0
  Test method: testShouldOutputGoodString
    Status: passed
    Time: 0.001

Test class: com.coveros.training.library.LibraryBorrowerListSearchServletTests
  Test method: testSearchNoBorrowers
    Status: passed
    Time: 0.019
  Test method: testSearchByNameNotFound
    Status: passed
    Time: 0.001
  Test method: testSearchById
    Status: passed
    Time: 0.002
  Test method: testListAllBorrowers_noBorrowersExist
    Status: passed
    Time: 0.001
  Test method: testListAllBorrowers
    Status: passed
    Time: 0.001
  Test method: testSearchByBadId
    Status: passed
    Time: 0.002
  Test method: testSearchBorrowerFoundById
    Status: passed
    Time: 0.001
  Test method: testSearchIdAndName
    Status: passed
    Time: 0.001
  Test method: testSearchNothingFoundByName
    Status: passed
    Time: 0.001
  Test method: testSearchByName
    Status: passed
    Time: 0.001
  Test method: testSearchNothingFoundById
    Status: passed
    Time: 0.001

Test class: com.coveros.training.mathematics.FibonacciParameterizedTests
  Test method: test[0]
    Status: passed
    Time: 0.0
  Test method: testIterative1[0]
    Status: passed
    Time: 0.0
  Test method: testIterative2[0]
    Status: passed
    Time: 0.0
  Test method: test[1]
    Status: passed
    Time: 0.0
  Test method: testIterative1[1]
    Status: passed
    Time: 0.0
  Test method: testIterative2[1]
    Status: passed
    Time: 0.0
  Test method: test[2]
    Status: passed
    Time: 0.0
  Test method: testIterative1[2]
    Status: passed
    Time: 0.0
  Test method: testIterative2[2]
    Status: passed
    Time: 0.0
  Test method: test[3]
    Status: passed
    Time: 0.0
  Test method: testIterative1[3]
    Status: passed
    Time: 0.0
  Test method: testIterative2[3]
    Status: passed
    Time: 0.0
  Test method: test[4]
    Status: passed
    Time: 0.0
  Test method: testIterative1[4]
    Status: passed
    Time: 0.0
  Test method: testIterative2[4]
    Status: passed
    Time: 0.0
  Test method: test[5]
    Status: passed
    Time: 0.001
  Test method: testIterative1[5]
    Status: passed
    Time: 0.0
  Test method: testIterative2[5]
    Status: passed
    Time: 0.0
  Test method: test[6]
    Status: passed
    Time: 0.0
  Test method: testIterative1[6]
    Status: passed
    Time: 0.0
  Test method: testIterative2[6]
    Status: passed
    Time: 0.001
  Test method: test[7]
    Status: passed
    Time: 0.0
  Test method: testIterative1[7]
    Status: passed
    Time: 0.0
  Test method: testIterative2[7]
    Status: passed
    Time: 0.0

Test class: com.coveros.training.authentication.LoginServletTests
  Test method: testHappyPathPost
    Status: passed
    Time: 0.711
  Test method: testEmptyString_Username
    Status: passed
    Time: 0.002
  Test method: testEmptyString_Password
    Status: passed
    Time: 0.001
  Test method: testShouldGetAccessDeniedIfUserNotRegistered
    Status: passed
    Time: 0.001

Test class: com.coveros.training.mathematics.AckermannParameterizedTests
  Test method: testShouldProperlyCalculate[0]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[1]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[2]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[3]
    Status: passed
    Time: 0.001
  Test method: testShouldProperlyCalculate[4]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[5]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[6]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[7]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[8]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[9]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[10]
    Status: passed
    Time: 0.0
  Test method: testShouldProperlyCalculate[11]
    Status: passed
    Time: 0.0

Test class: com.coveros.training.mathematics.FibServletTests
  Test method: testPostService_tailRecursive1
    Status: passed
    Time: 0.015
  Test method: testPostService_tailRecursive2
    Status: passed
    Time: 0.001
  Test method: testPostService_HappyPath
    Status: passed
    Time: 0.001
  Test method: testPostService_realForward_withException
    Status: passed
    Time: 0.001
  Test method: testPostService_Forward
    Status: passed
    Time: 0.0

Test class: com.coveros.training.helpers.StringUtilsTests
  Test method: testEscapeForJson_ShouldEscapeBackslash
    Status: passed
    Time: 0.0
  Test method: testShouldNotAlterNonNullString
    Status: passed
    Time: 0.001
  Test method: testShouldConvertNullToEmptyString
    Status: passed
    Time: 0.0
  Test method: testEscapeForJson_ShouldEscapeDoubleQuote

In [61]:
df_mono.shape

(322, 6)

In [63]:
df_mono

,app,ms_name_or_monolith,test_class,test_method,status,time
0,spring-petclinic,monolith,org.springframework.samples.petclinic.owner.Ow...,testProcessUpdateOwnerFormHasErrors,passed,0.350
1,spring-petclinic,monolith,org.springframework.samples.petclinic.owner.Ow...,testProcessCreationFormSuccess,passed,0.006
2,spring-petclinic,monolith,org.springframework.samples.petclinic.owner.Ow...,testInitFindForm,passed,0.010
3,spring-petclinic,monolith,org.springframework.samples.petclinic.owner.Ow...,testShowOwner,passed,0.031
4,spring-petclinic,monolith,org.springframework.samples.petclinic.owner.Ow...,testInitUpdateOwnerForm,passed,0.012
...,...,...,...,...,...,...
317,7ep-demo,monolith,com.coveros.training.mathematics.FibonacciTests,testLargerValuesFibAlgo2,passed,0.001
318,7ep-demo,monolith,com.coveros.training.mathematics.FibonacciTests,testSmallValuesFibAlgo1,passed,0.000
319,7ep-demo,monolith,com.coveros.training.mathematics.FibonacciTests,testSmallValuesFibAlgo2,passed,0.000
320,7ep-demo,monolith,com.coveros.training.mathematics.FibonacciTests,testLargeValuesFibAlgo1,passed,0.000
321,7ep-demo,monolith,com.coveros.training.mathematics.FibonacciTests,testLargeValuesFibAlgo2,passed,0.000

### MicroRefact

In [36]:
columns = ["app", "ms_name_or_monolith", "test_class", "test_method", "status", "time"]
reports_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports"

rows = []
rows_per_ms = {}

for app in ["spring-petclinic", "jpetstore-6", "7ep-demo"]:
    app_report_path = Path(f"{reports_path}/microrefact/{app}")
    print(f"Testing {app}...")
    rows_per_ms[app] = {}
    microservices = [i for i in os.listdir(app_report_path) if not i.startswith(".") and os.path.isdir(os.path.join(app_report_path, i))]
    for ms in microservices:
        rows_per_ms[app][ms] = []
        parser = ReportParser()
        report = parser.extract(app_report_path/ms)
        print(f"Report for {app}/{ms}:")
        for test_class in report:
            # print(f"Test class: {test_class}")
            for test_method in report[test_class]['test_cases']:
                # print(f"  Test method: {test_method}")
                # print(f"    Status: {report[test_class]['test_cases'][test_method]['status']}")
                # print(f"    Time: {report[test_class]['test_cases'][test_method]['time']}")
                rows.append({
                    "app": app,
                    "ms_name_or_monolith": ms,
                    "test_class": test_class,
                    "test_method": test_method,
                    "status": report[test_class]['test_cases'][test_method]['status'],
                    "time": report[test_class]['test_cases'][test_method]['time'],
                })
                rows_per_ms[app][ms].append(report[test_class]['test_cases'][test_method]['status'])
            # print()
        print("="*100)
        print()
    print("="*100)
    print()

df_microrefact = pd.DataFrame(rows, columns=columns)

INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.owner.OwnerControllerTests.xml for class org.springframework.samples.petclinic.owner.OwnerControllerTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.owner.PetControllerTests.xml for class org.springframework.samples.petclinic.owner.PetControllerTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml for class org.springframework.samples.petclinic.model.ValidatorTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.service.ClinicServiceTests.xml for class org.springframework.samples.petclinic.service.ClinicServiceTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.system.CrashControllerTests.xml for class org.springframework.samples.petclinic.system.CrashControllerTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.owner.PetTypeFormatterTests.xml for class org.springframework.samples.petclinic.owner.PetTypeFormatterTests
DEBUG:refacteval:Parsed reports: 6
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.vet.VetControllerTests.xml for class org.springframework.samples.petclinic.vet.VetControllerTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.vet.VetTests.xml for class org.springframework.samples.petclinic.vet.VetTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml for class org.springframework.samples.petclinic.model.ValidatorTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.service.ClinicServiceTests.xml for class org.springframework.samples.petclinic.service.ClinicServiceTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.system.CrashControllerTests.xml for class org.springframework.samples.petclinic.system.CrashControllerTests
DEBUG:refacteval:Parsed reports: 5
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.model.ValidatorTests.xml for class org.springframework.samples.petclinic.model.ValidatorTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.owner.VisitControllerTests.xml for class org.springframework.samples.petclinic.owner.VisitControllerTests
INFO:refacteval:Parsing report TEST-org.springframework.samples.petclinic.system.CrashControllerTests.xml for class org.springframework.samples.petclinic.system.CrashControllerTests
DEBUG:refacteval:Parsed reports: 3
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.mapper.AccountMapperTest.xml for class org.mybatis.jpetstore.mapper.AccountMapperTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.service.AccountServiceTest.xml for class org.mybatis.jpetstore.service.AccountServiceTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.web.actions.AccountActionBeanTest.xml for class org.mybatis.jpetstore.web.actions.AccountActionBeanTest
DEBUG:refacteval:Parsed reports: 3
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.web.actions.CatalogActionBeanTest.xml for class org.mybatis.jpetstore.web.actions.CatalogActionBeanTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.mapper.CategoryMapperTest.xml for class org.mybatis.jpetstore.mapper.CategoryMapperTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.service.CatalogServiceTest.xml for class org.mybatis.jpetstore.service.CatalogServiceTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.mapper.ItemMapperTest.xml for class org.mybatis.jpetstore.mapper.ItemMapperTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.mapper.ProductMapperTest.xml for class org.mybatis.jpetstore.mapper.ProductMapperTest
DEBUG:refacteval:Parsed reports: 5
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.mapper.OrderMapperTest.xml for class org.mybatis.jpetstore.mapper.OrderMapperTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.mapper.LineItemMapperTest.xml for class org.mybatis.jpetstore.mapper.LineItemMapperTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.web.actions.OrderActionBeanTest.xml for class org.mybatis.jpetstore.web.actions.OrderActionBeanTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.domain.CartTest.xml for class org.mybatis.jpetstore.domain.CartTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.mapper.SequenceMapperTest.xml for class org.mybatis.jpetstore.mapper.SequenceMapperTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.service.OrderServiceTest.xml for class org.mybatis.jpetstore.service.OrderServiceTest
INFO:refacteval:Parsing report TEST-org.mybatis.jpetstore.domain.OrderTest.xml for class org.mybatis.jpetstore.domain.OrderTest
DEBUG:refacteval:Parsed reports: 7
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.RegisterServletTests.xml for class com.coveros.training.authentication.RegisterServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.RegistrationUtilsTests.xml for class com.coveros.training.authentication.RegistrationUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.LoginUtilsTests.xml for class com.coveros.training.authentication.LoginUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.domainobjects.UserTests.xml for class com.coveros.training.authentication.domainobjects.UserTests
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.LoginServletTests.xml for class com.coveros.training.authentication.LoginServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.helpers.StringUtilsTests.xml for class com.coveros.training.helpers.StringUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.ParameterObjectTests.xml for class com.coveros.training.persistence.ParameterObjectTests
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.domainobjects.PasswordResultTests.xml for class com.coveros.training.authentication.domainobjects.PasswordResultTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.SqlDataTests.xml for class com.coveros.training.persistence.SqlDataTests
INFO:refacteval:Parsing report TEST-com.coveros.training.helpers.CheckUtilsTests.xml for class com.coveros.training.helpers.CheckUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.tomcat.WebAppListenerTests.xml for class com.coveros.training.tomcat.WebAppListenerTests
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.NbvcxzTests.xml for class com.coveros.training.authentication.NbvcxzTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.EmptyDataSourceTests.xml for class com.coveros.training.persistence.EmptyDataSourceTests
INFO:refacteval:Parsing report TEST-com.coveros.training.authentication.domainobjects.RegistrationResultTests.xml for class com.coveros.training.authentication.domainobjects.RegistrationResultTests
DEBUG:refacteval:Parsed reports: 14
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LibraryLendServletTests.xml for class com.coveros.training.library.LibraryLendServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LibraryUtilsTests.xml for class com.coveros.training.library.LibraryUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.domainobjects.BookTests.xml for class com.coveros.training.library.domainobjects.BookTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LibraryBorrowerListSearchServletTests.xml for class com.coveros.training.library.LibraryBorrowerListSearchServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.helpers.StringUtilsTests.xml for class com.coveros.training.helpers.StringUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LibraryBookListAvailableServletTests.xml for class com.coveros.training.library.LibraryBookListAvailableServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.ParameterObjectTests.xml for class com.coveros.training.persistence.ParameterObjectTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LibraryBookListSearchServletTests.xml for class com.coveros.training.library.LibraryBookListSearchServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LibraryRegisterBorrowerServletTests.xml for class com.coveros.training.library.LibraryRegisterBorrowerServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LendingTests.xml for class com.coveros.training.library.LendingTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.LibraryRegisterBookServletTests.xml for class com.coveros.training.library.LibraryRegisterBookServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.domainobjects.LoanTests.xml for class com.coveros.training.library.domainobjects.LoanTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.SqlDataTests.xml for class com.coveros.training.persistence.SqlDataTests
INFO:refacteval:Parsing report TEST-com.coveros.training.tomcat.WebAppListenerTests.xml for class com.coveros.training.tomcat.WebAppListenerTests
INFO:refacteval:Parsing report TEST-com.coveros.training.library.domainobjects.BorrowerTests.xml for class com.coveros.training.library.domainobjects.BorrowerTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.EmptyDataSourceTests.xml for class com.coveros.training.persistence.EmptyDataSourceTests
DEBUG:refacteval:Parsed reports: 16
INFO:refacteval:Parsing report TEST-com.coveros.training.helpers.StringUtilsTests.xml for class com.coveros.training.helpers.StringUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.ParameterObjectTests.xml for class com.coveros.training.persistence.ParameterObjectTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.SqlDataTests.xml for class com.coveros.training.persistence.SqlDataTests
INFO:refacteval:Parsing report TEST-com.coveros.training.helpers.CheckUtilsTests.xml for class com.coveros.training.helpers.CheckUtilsTests
INFO:refacteval:Parsing report TEST-com.coveros.training.tomcat.WebAppListenerTests.xml for class com.coveros.training.tomcat.WebAppListenerTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.EmptyDataSourceTests.xml for class com.coveros.training.persistence.EmptyDataSourceTests
INFO:refacteval:Parsing report TEST-com.coveros.training.persistence.DbServletTests.xml for class com.coveros.training.persistence.DbServletTests
DEBUG:refacteval:Parsed reports: 7
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.MathServletTests.xml for class com.coveros.training.mathematics.MathServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.AckServletTests.xml for class com.coveros.training.mathematics.AckServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.FibonacciParameterizedTests.xml for class com.coveros.training.mathematics.FibonacciParameterizedTests
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.AckermannParameterizedTests.xml for class com.coveros.training.mathematics.AckermannParameterizedTests
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.FibServletTests.xml for class com.coveros.training.mathematics.FibServletTests
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.AckermannIterativeParameterizedTests.xml for class com.coveros.training.mathematics.AckermannIterativeParameterizedTests
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.CalculatorTests.xml for class com.coveros.training.mathematics.CalculatorTests
INFO:refacteval:Parsing report TEST-com.coveros.training.mathematics.FibonacciTests.xml for class com.coveros.training.mathematics.FibonacciTests
DEBUG:refacteval:Parsed reports: 8

Testing spring-petclinic...
Report for spring-petclinic/0:
====================================================================================================

Report for spring-petclinic/1:
====================================================================================================

Report for spring-petclinic/2:
====================================================================================================

====================================================================================================

Testing jpetstore-6...
Report for jpetstore-6/0:
====================================================================================================

Report for jpetstore-6/1:
====================================================================================================

Report for jpetstore-6/2:
====================================================================================================

====================================================================================================

Testing 7ep-demo...
Report for 7ep-demo/0:
====================================================================================================

Report for 7ep-demo/1:
====================================================================================================

Report for 7ep-demo/3:
====================================================================================================

Report for 7ep-demo/2:
====================================================================================================

====================================================================================================

In [37]:
df_microrefact.shape

(387, 6)

In [75]:
for app in rows_per_app:
    print(f"App: {app}: {len(rows_per_app[app])}")

App: spring-petclinic: 41
App: jpetstore-6: 74
App: 7ep-demo: 207

In [40]:
for app in rows_per_ms:
    sum = 0
    for ms in rows_per_ms[app]:
        print(f"App: {app}/{ms}: {len(rows_per_ms[app][ms])}")
        sum += len(rows_per_ms[app][ms])
    print(f"App: {app}/all: {sum}")
    print()

App: spring-petclinic/0: 33
App: spring-petclinic/1: 15
App: spring-petclinic/2: 5
App: spring-petclinic/all: 53

App: jpetstore-6/0: 18
App: jpetstore-6/1: 29
App: jpetstore-6/2: 27
App: jpetstore-6/all: 74

App: 7ep-demo/0: 61
App: 7ep-demo/1: 94
App: 7ep-demo/3: 32
App: 7ep-demo/2: 73
App: 7ep-demo/all: 260

In [41]:
save_path = f"{reports_path}/parsed_reports_microrefact.csv"
df_microrefact.to_csv(save_path, index=False)

## Analyze the results

In [42]:
import pandas as pd

monolith_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/parsed_reports_monoliths.csv"
microservices_path = "/Users/khalsel/Documents/projects/MonoRefact/MonoRefact/data/refacteval-final/testing-apps/reports/parsed_reports_microrefact.csv"

df_mono = pd.read_csv(monolith_path)
df_microrefact = pd.read_csv(microservices_path)

In [43]:
mono_tests = df_mono.apply(lambda row: f"{row['app']}::{row['test_class']}::{row['test_method']}", axis=1).tolist()
df_mono_indexed = df_mono.copy()
df_mono_indexed["test_fqn"] = mono_tests
df_mono_indexed.set_index("test_fqn", inplace=True)
mm_tests = df_microrefact.apply(lambda row: f"{row['app']}::{row['test_class']}::{row['test_method']}", axis=1).tolist()
df_microrefact["test_fqn"] = mm_tests

In [44]:
rows = []

for app in df_microrefact["app"].unique():
    dft = df_microrefact[df_microrefact.app==app]
    for ms in dft["ms_name_or_monolith"].unique():
        dft2 = dft[(dft.ms_name_or_monolith==ms)]
        count = len(dft2)
        mono_dft2 = df_mono_indexed.loc[dft2["test_fqn"]]
        matching_tests_index = dft2.apply(lambda row: row["status"]==mono_dft2.loc[row["test_fqn"], "status"], axis=1)
        matching_tests_count = matching_tests_index.sum()
        passed_tests = dft2[dft2.status == "passed"]
        mono_passed_tests = df_mono_indexed.loc[passed_tests["test_fqn"]]
        passed_count = len(passed_tests)
        total_test_count = len(dft2)
        total_time = passed_tests["time"].sum()
        avg_time = passed_tests["time"].mean() if passed_count > 0 else 0
        mono_total_time = mono_passed_tests["time"].sum()
        mono_avg_time = mono_passed_tests["time"].mean() if passed_count > 0 else 0
        rows.append({
            "app": app,
            "ms_name_or_monolith": ms,
            "matching_tests_count": matching_tests_count,
            "passed_tests_count": passed_count,
            "total_test_count": total_test_count,
            "fpr": matching_tests_count / total_test_count if total_test_count > 0 else 0,
            "passed_total_time": total_time,
            "passed_avg_time": avg_time,
            "passed_mono_total_time": mono_total_time,
            "passed_mono_avg_time": mono_avg_time,
        })
df_summary = pd.DataFrame(rows, columns=["app", "ms_name_or_monolith", "matching_tests_count", "passed_tests_count", "total_test_count", "fpr", "passed_total_time", "passed_avg_time", "passed_mono_total_time", "passed_mono_avg_time"])
df_summary

,app,ms_name_or_monolith,matching_tests_count,passed_tests_count,total_test_count,fpr,passed_total_time,passed_avg_time,passed_mono_total_time,passed_mono_avg_time
0,spring-petclinic,0,23,22,33,0.696970,1.072,0.048727,0.542,0.024636
1,spring-petclinic,1,5,4,15,0.333333,0.841,0.210250,0.079,0.019750
2,spring-petclinic,2,2,1,5,0.400000,0.392,0.392000,0.003,0.003000
3,jpetstore-6,0,15,15,18,0.833333,0.878,0.058533,0.737,0.049133
4,jpetstore-6,1,29,29,29,1.000000,1.041,0.035897,0.092,0.003172
5,jpetstore-6,2,16,16,27,0.592593,0.952,0.059500,0.204,0.012750
6,7ep-demo,0,50,46,61,0.819672,0.609,0.013239,0.533,0.011587
7,7ep-demo,1,36,36,94,0.382979,0.167,0.004639,0.098,0.002722
8,7ep-demo,3,27,27,32,0.843750,0.137,0.005074,0.072,0.002667
9,7ep-demo,2,68,62,73,0.931507,0.197,0.003177,0.138,0.002226

In [45]:
df_summary = df_summary[["app", "ms_name_or_monolith", "matching_tests_count", "passed_tests_count", "total_test_count", "fpr"]]
overall_rows = []
for app in df_summary["app"].unique():
    dft = df_summary[df_summary.app==app]
    overall_rows.append({
        "app": app,
        "ms_name_or_monolith": "Overall",
        "matching_tests_count": dft["matching_tests_count"].sum(),
        "passed_tests_count": dft["passed_tests_count"].sum(),
        "total_test_count": dft["total_test_count"].sum(),
        "fpr": dft["matching_tests_count"].sum() / dft["total_test_count"].sum() if dft["total_test_count"].sum() > 0 else 0,
    })
all_overall_row = {
    "app": "Overall",
    "ms_name_or_monolith": "Overall",
    "matching_tests_count": df_summary["matching_tests_count"].sum(),
    "passed_tests_count": df_summary["passed_tests_count"].sum(),
    "total_test_count": df_summary["total_test_count"].sum(),
    "fpr": df_summary["matching_tests_count"].sum() / df_summary["total_test_count"].sum() if df_summary["total_test_count"].sum() > 0 else 0,
}
overall_rows.append(all_overall_row)
df_overall_summary = pd.concat([
    df_summary,
    pd.DataFrame(overall_rows, columns=df_summary.columns),
], ignore_index=True)
# sort by app and ms_name_or_monolith but the overall row should be at the end of each app and then the overall row at the end
df_overall_summary["app"] = df_overall_summary["app"].astype(str)
df_overall_summary["ms_name_or_monolith"] = df_overall_summary["ms_name_or_monolith"].astype(str)
df_overall_summary["app"] = df_overall_summary["app"].apply(lambda x: x if x != "Overall" else "zZZ_Overall")
df_overall_summary["ms_name_or_monolith"] = df_overall_summary["ms_name_or_monolith"].apply(lambda x: x if x != "Overall" else "zZZ_Overall")
df_overall_summary = df_overall_summary.sort_values(["app", "ms_name_or_monolith"])
df_overall_summary["app"] = df_overall_summary["app"].apply(lambda x: x if x != "zZZ_Overall" else "Overall")
df_overall_summary["ms_name_or_monolith"] = df_overall_summary["ms_name_or_monolith"].apply(lambda x: x if x != "zZZ_Overall" else "Overall")
# sort by app
df_overall_summary

,app,ms_name_or_monolith,matching_tests_count,passed_tests_count,total_test_count,fpr
6,7ep-demo,0,50,46,61,0.819672
7,7ep-demo,1,36,36,94,0.382979
9,7ep-demo,2,68,62,73,0.931507
8,7ep-demo,3,27,27,32,0.843750
12,7ep-demo,Overall,181,171,260,0.696154
3,jpetstore-6,0,15,15,18,0.833333
4,jpetstore-6,1,29,29,29,1.000000
5,jpetstore-6,2,16,16,27,0.592593
11,jpetstore-6,Overall,60,60,74,0.810811
0,spring-petclinic,0,23,22,33,0.696970
1,spring-petclinic,1,5,4,15,0.333333
2,spring-petclinic,2,2,1,5,0.400000
10,spring-petclinic,Overall,30,27,53,0.566038
13,Overall,Overall,271,258,387,0.700258

In [48]:
# Format the DataFrame to display as a table in latex

df_overall_summary_latex = df_overall_summary.copy()
df_overall_summary_latex = df_overall_summary_latex.rename(columns={
    "matching_tests_count": "Matching Tests",
    "passed_tests_count": "Passed Tests",
    "total_test_count": "Total Tests",
    "fpr": "FPR",
    "ms_name_or_monolith": "Microservice",
    "app": "Application",
})
df_overall_summary_latex["Microservice"] = df_overall_summary_latex.apply(lambda x: microservice_id_name_map[x["Application"]][x["Microservice"]] if x["Microservice"] != "Overall" else x["Microservice"], axis=1)
df_overall_summary_latex.replace(
    {
        'Application': {
            'spring-petclinic': 'PetClinic',
            'jpetstore-6': 'JPetStore',
            '7ep-demo': '7ep Demo',
        }
    },
    inplace=True
)
df_overall_summary_latex["Microservice"] = df_overall_summary_latex["Microservice"].apply(lambda x: x.title())
df_overall_summary_latex = df_overall_summary_latex.set_index(['Application', 'Microservice'])
df_overall_summary_latex["FPR"] = df_overall_summary_latex["FPR"].apply(lambda x: f"{x*100:.1f}\\%")
df_overall_summary_latex = df_overall_summary_latex.style.format({
    'Matching Tests': '{:,.0f}',
    'Passed Tests': '{:,.0f}',
    'Total Tests': '{:,.0f}',
    # 'FPR': '{:.1%}',
})
df_overall_summary_latex

In [50]:
df_overall_summary_latex_str = df_overall_summary_latex.to_latex(
    hrules=True,
    label="tab-mm:test_results_microrefact",
    caption="Test Outcome Equivalence Results for MicroRefact Microservices",
    position="htbp",
    column_format="ll|cccc",
)
print(df_overall_summary_latex_str)

\begin{table}[htbp]
\caption{Test Outcome Equivalence Results for MicroRefact Microservices}
\label{tab-mm:test_results_microrefact}
\begin{tabular}{ll|cccc}
\toprule
 &  & Matching Tests & Passed Tests & Total Tests & FPR \\
Application & Microservice &  &  &  &  \\
\midrule
\multirow[c]{5}{*}{7ep Demo} & Authentication & 50 & 46 & 61 & 82.0\% \\
 & Library & 36 & 36 & 94 & 38.3\% \\
 & Mathematics & 68 & 62 & 73 & 93.2\% \\
 & Persistence & 27 & 27 & 32 & 84.4\% \\
 & Overall & 181 & 171 & 260 & 69.6\% \\
\multirow[c]{4}{*}{JPetStore} & Account & 15 & 15 & 18 & 83.3\% \\
 & Catalog & 29 & 29 & 29 & 100.0\% \\
 & Order & 16 & 16 & 27 & 59.3\% \\
 & Overall & 60 & 60 & 74 & 81.1\% \\
\multirow[c]{4}{*}{PetClinic} & Customers & 23 & 22 & 33 & 69.7\% \\
 & Vets & 5 & 4 & 15 & 33.3\% \\
 & Visits & 2 & 1 & 5 & 40.0\% \\
 & Overall & 30 & 27 & 53 & 56.6\% \\
Overall & Overall & 271 & 258 & 387 & 70.0\% \\
\bottomrule
\end{tabular}
\end{table}

In [22]:
failed_rows = []

for app in df_microrefact["app"].unique():
    dft = df_microrefact[df_microrefact.app==app]
    for ms in dft["ms_name_or_monolith"].unique():
        dft2 = dft[(dft.ms_name_or_monolith==ms)]
        count = len(dft2)
        mono_dft2 = df_mono_indexed.loc[dft2["test_fqn"]]
        non_matching_tests_index = ~dft2.apply(lambda row: row["status"]==mono_dft2.loc[row["test_fqn"], "status"], axis=1)
        failed_rows.append(dft2[non_matching_tests_index])
df_non_matching = pd.concat(failed_rows, ignore_index=True)
df_non_matching

,app,ms_name_or_monolith,test_class,test_method,status,time,test_fqn
0,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldFindVets,errored,0.000,spring-petclinic::org.springframework.samples....
1,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldFindOwnersByLastName,errored,0.001,spring-petclinic::org.springframework.samples....
2,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldAddNewVisitForPet,errored,0.000,spring-petclinic::org.springframework.samples....
3,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldUpdateOwner,errored,0.001,spring-petclinic::org.springframework.samples....
4,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldFindVisitsByPetId,errored,0.001,spring-petclinic::org.springframework.samples....
5,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldInsertPetIntoDatabaseAndGenerateId,errored,0.001,spring-petclinic::org.springframework.samples....
6,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldInsertOwner,errored,0.000,spring-petclinic::org.springframework.samples....
7,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldFindSingleOwnerWithPet,errored,0.001,spring-petclinic::org.springframework.samples....
8,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldUpdatePetName,errored,0.001,spring-petclinic::org.springframework.samples....
9,spring-petclinic,customers,org.springframework.samples.petclinic.service....,shouldFindAllPetTypes,errored,0.000,spring-petclinic::org.springframework.samples....
10,spring-petclinic,visits,org.springframework.samples.petclinic.owner.Vi...,testProcessNewVisitFormHasErrors,errored,0.000,spring-petclinic::org.springframework.samples....
11,spring-petclinic,visits,org.springframework.samples.petclinic.owner.Vi...,testProcessNewVisitFormSuccess,errored,0.001,spring-petclinic::org.springframework.samples....
12,spring-petclinic,visits,org.springframework.samples.petclinic.owner.Vi...,testInitNewVisitForm,errored,0.000,spring-petclinic::org.springframework.samples....
13,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldFindVets,errored,0.000,spring-petclinic::org.springframework.samples....
14,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldFindOwnersByLastName,errored,0.000,spring-petclinic::org.springframework.samples....
15,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldAddNewVisitForPet,errored,0.000,spring-petclinic::org.springframework.samples....
16,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldUpdateOwner,errored,0.000,spring-petclinic::org.springframework.samples....
17,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldFindVisitsByPetId,errored,0.000,spring-petclinic::org.springframework.samples....
18,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldInsertPetIntoDatabaseAndGenerateId,errored,0.000,spring-petclinic::org.springframework.samples....
19,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldInsertOwner,errored,0.000,spring-petclinic::org.springframework.samples....
20,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldFindSingleOwnerWithPet,errored,0.000,spring-petclinic::org.springframework.samples....
21,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldUpdatePetName,errored,0.000,spring-petclinic::org.springframework.samples....
22,spring-petclinic,vets,org.springframework.samples.petclinic.service....,shouldFindAllPetTypes,errored,0.000,spring-petclinic::org.springframework.samples....

In [23]:
df_non_matching["test_class"].unique()

array(['org.springframework.samples.petclinic.service.ClinicServiceTests',
       'org.springframework.samples.petclinic.owner.VisitControllerTests'],
      dtype=object)